const questions=[
{q:"Em uma questão de interpretação, a resposta deve se apoiar principalmente em:",a:["Sua opinião pessoal","O texto apresentado","A alternativa mais longa","O que outras pessoas pensam"],c:1,e:"A interpretação deve ser sustentada pelo texto."},
{q:"A ideia principal de um texto é:",a:["A mensagem central desenvolvida","Sempre a primeira frase","A palavra mais repetida","A opinião do leitor"],c:0,e:"A ideia principal representa o núcleo da mensagem."},
{q:"O texto diz: “Marina levou casaco porque a temperatura caiu.” O que é seguro concluir?",a:["Marina comprou o casaco hoje","A temperatura estava mais baixa","Marina odeia frio","Era madrugada"],c:1,e:"Somente a queda da temperatura está sustentada pela frase."},
{q:"Antes de marcar uma alternativa, uma boa estratégia é:",a:["Inventar detalhes","Confirmar a resposta no texto","Escolher rapidamente","Ignorar o enunciado"],c:1,e:"Voltar ao texto ajuda a evitar conclusões sem fundamento."},
{q:"Qual atitude pode causar erro de interpretação?",a:["Identificar palavras-chave","Ler o comando","Responder pela própria opinião sem conferir o texto","Procurar a ideia central"],c:2,e:"A opinião pessoal não substitui as informações fornecidas pelo texto."}
];let qi=0,score=0,errors=[],answered=false;
function show(id){document.querySelectorAll(".page").forEach(x=>x.classList.remove("active"));document.getElementById(id).classList.add("active");document.querySelectorAll("nav button").forEach(x=>x.classList.toggle("active",x.dataset.page===id));scrollTo(0,0)}
function startQuiz(){qi=0;score=0;errors=[];show("quiz");renderQ()}
function renderQ(){answered=false;let q=questions[qi];qnum.textContent=`QUESTÃO ${qi+1} DE ${questions.length}`;scoreNow.textContent=`${score} acertos`;qbar.style.width=`${(qi+1)/questions.length*100}%`;qtext.textContent=q.q;answers.innerHTML="";q.a.forEach((t,i)=>{let b=document.createElement("button");b.className="answer";b.textContent=String.fromCharCode(65+i)+". "+t;b.onclick=()=>answer(i,b);answers.appendChild(b)});feedback.classList.add("hidden");next.classList.add("hidden");next.textContent=qi===questions.length-1?"VER RESULTADO":"PRÓXIMA"}
function answer(i,b){if(answered)return;answered=true;let q=questions[qi],bs=[...document.querySelectorAll(".answer")];bs.forEach(x=>x.disabled=true);if(i===q.c){score++;b.classList.add("ok")}else{b.classList.add("no");bs[q.c].classList.add("ok");errors.push(q.q)}feedback.textContent=q.e;feedback.classList.remove("hidden");next.classList.remove("hidden");scoreNow.textContent=`${score} acertos`}
function nextQ(){if(qi<questions.length-1){qi++;renderQ()}else{let p=Math.round(score/questions.length*100);resultPct.textContent=p+"%";resultScore.textContent=`${score}/${questions.length}`;if(p>=90){resultTitle.textContent="Dominado 🟢";resultMsg.textContent="Excelente desempenho.";mastery.textContent="DOMÍNIO: assunto dominado"}else if(p>=70){resultTitle.textContent="Bom trabalho 🟡";resultMsg.textContent="Você pode avançar, mas seus erros entrarão na revisão.";mastery.textContent="DOMÍNIO: bom"}else if(p>=50){resultTitle.textContent="Precisamos revisar 🟠";resultMsg.textContent="O assunto voltará para sua fila de revisão.";mastery.textContent="DOMÍNIO: revisão necessária"}else{resultTitle.textContent="Vamos reforçar a base 🔴";resultMsg.textContent="Sem problema: revise a aula e tente novamente.";mastery.textContent="DOMÍNIO: refazer conteúdo"}localStorage.setItem("lastScore",p);localStorage.setItem("errors",JSON.stringify(errors));localStorage.setItem("tested","1");sync();show("result")}}
function finishMission(){let x=Number(localStorage.getItem("xp")||0)+100;localStorage.setItem("xp",x);localStorage.setItem("mission","1");localStorage.setItem("port","10");sync();show("progressPage")}
function sync(){let x=localStorage.getItem("xp")||0,s=localStorage.getItem("lastScore"),m=localStorage.getItem("mission"),t=localStorage.getItem("tested"),p=localStorage.getItem("port")||0,e=JSON.parse(localStorage.getItem("errors")||"[]");xp.textContent=x;general.textContent=p+"%";portPct.textContent=p+"%";pPct.textContent=p+"%";pbar.style.width=p+"%";if(m){missions.textContent="1";aMission.textContent="✅ Completei minha primeira missão"}if(t)aTest.textContent="✅ Completei meu primeiro teste";errorBook.innerHTML=e.length?e.map((v,i)=>`${i+1}. ${v}`).join("<br><br>"):"Nenhum erro registrado na última bateria."}sync();
