(function(){
'use strict';
const KEY='pmmg_edital_map_v102';
const groups=[
 {id:'portugues',name:'Língua Portuguesa e Interpretação de Textos',icon:'📘',items:[
  'Adequação conceitual','Pertinência, relevância e articulação dos argumentos','Seleção vocabular','Estudo de texto','Tipologia textual e gêneros textuais','Ortografia oficial','Acentuação gráfica','Emprego dos sinais de pontuação','Estrutura e formação de palavras','Classes de palavras','Frase, oração e período','Termos da oração','Período composto por coordenação e subordinação','Funções sintáticas dos pronomes relativos','Emprego de nomes e pronomes','Emprego de tempos e modos verbais','Regência verbal e nominal','Concordância verbal e nominal','Orações reduzidas','Colocação pronominal','Estilística','Figuras de linguagem','Vícios de linguagem e qualidade da boa linguagem','Fonemas','Semântica','Emprego da crase','Sintaxe: regência, concordância e colocação','Coesão e coerência textuais']},
 {id:'literatura',name:'Literatura',icon:'📚',items:['Campo Geral — João Guimarães Rosa','Vidas Secas — Graciliano Ramos']},
 {id:'ingles',name:'Noções de Língua Inglesa',icon:'🇬🇧',items:['Compreensão e interpretação de texto escrito em língua inglesa','Itens gramaticais relevantes para a compreensão dos conteúdos semânticos']},
 {id:'direito',name:'Noções de Direito e Direitos Humanos',icon:'⚖️',items:[
  'CF/88 — Título I: Dos Princípios Fundamentais','CF/88 — Direitos e Deveres Individuais e Coletivos','CF/88 — Nacionalidade','CF/88 — Direitos Políticos','CF/88 — Administração Pública: Disposições Gerais','CF/88 — Militares dos Estados, DF e Territórios','CF/88 — Tribunais e Juízes Militares','CF/88 — Tribunais e Juízes dos Estados','CF/88 — Forças Armadas','CF/88 — Segurança Pública','LINDB — Lei nº 4.657/1942','Declaração Universal dos Direitos Humanos','Convenção Americana sobre Direitos Humanos — Pacto de San José']},
 {id:'matematica',name:'Raciocínio Lógico-Matemático',icon:'🧮',items:[
  'Representações: figuras planas, desenhos, mapas, gráficos, tabelas, séries e plantas; escalas','Estatística: população, universo, amostra, amostragem, variáveis, tendência central, dispersão e porcentagem','Estruturas e diagramas lógicos; lógica de primeira ordem','Lógica de argumentação: analogias, inferências, deduções e conclusões','Lógica proposicional: tautologias, contradições, contingências, proposições e tabelas-verdade','Equivalências, implicações, Leis de Morgan e silogismos','Métrica: áreas, volumes, estimativas e aplicações','Equações de 1º e 2º graus e sistemas lineares','Contagem, probabilidade e estatística','Funções: análise gráfica, afim, quadrática, exponencial e logarítmica','Operações com conjuntos','Sequências numéricas, PA e PG','Razão, proporção e regra de três simples e composta']}
];
function load(){try{return JSON.parse(localStorage.getItem(KEY)||'{}')}catch(e){return {}}}
function save(x){localStorage.setItem(KEY,JSON.stringify(x))}
function key(g,i){return g+'_'+i}
function status(g,i){return load()[key(g,i)]||0}
window.cycleEditalStatusV102=function(g,i){const d=load(),k=key(g,i);d[k]=((d[k]||0)+1)%3;save(d);renderEditalMapV102()}
window.openEditalMapV102=function(){if(typeof showScreen==='function')showScreen('editalMapV102Screen','navStudy');renderEditalMapV102()}
window.renderEditalMapV102=function(){
 const root=document.getElementById('v102EditalSubjects'); if(!root)return;
 const subj=document.getElementById('v102EditalSubject')?.value||'all', filter=document.getElementById('v102EditalFilter')?.value||'all';
 let total=0,studying=0,done=0; groups.forEach(g=>g.items.forEach((_,i)=>{total++;const st=status(g.id,i);if(st===1)studying++;if(st===2)done++}));
 const pct=Math.round(done/total*100);
 document.getElementById('v102EditalStats').innerHTML=`<article><strong>${pct}%</strong><small>DOMÍNIO</small></article><article><strong>${done}/${total}</strong><small>DOMINADOS</small></article><article><strong>${studying}</strong><small>ESTUDANDO</small></article><article><strong>${total-done-studying}</strong><small>NÃO INICIADOS</small></article><div class="v102-edital-bar"><i style="width:${pct}%"></i></div>`;
 const labels=['○ Não iniciado','◐ Estudando','✓ Dominado'];
 root.innerHTML=groups.filter(g=>subj==='all'||g.id===subj).map(g=>{
  const rows=g.items.map((t,i)=>{const st=status(g.id,i);if(filter==='pending'&&st!==0)return'';if(filter==='studying'&&st!==1)return'';if(filter==='done'&&st!==2)return'';return `<button class="v102-topic s${st}" onclick="cycleEditalStatusV102('${g.id}',${i})"><span>${t}</span><b>${labels[st]}</b></button>`}).join('');
  if(!rows)return''; const gd=g.items.filter((_,i)=>status(g.id,i)===2).length; return `<section class="v102-edital-group"><div class="v102-edital-title"><span>${g.icon}</span><div><h3>${g.name}</h3><small>${gd} de ${g.items.length} dominados</small></div></div>${rows}</section>`
 }).join('')||'<div class="empty-state">Nenhum tópico neste filtro.</div>';
}
const css=document.createElement('style');css.textContent=`
.v102-edital-entry{margin:14px 0 18px;padding:17px;border:1px solid rgba(168,139,250,.35);border-radius:18px;background:linear-gradient(135deg,rgba(124,58,237,.14),rgba(10,15,25,.8));display:flex;align-items:center;justify-content:space-between;gap:12px;cursor:pointer}.v102-edital-entry h3{margin:4px 0}.v102-edital-entry p{margin:0;opacity:.72;font-size:13px}.v102-edital-entry>b{font-size:26px}.v102-edital-screen{padding-bottom:110px}.v102-edital-hero{display:flex;gap:13px;align-items:center;padding:16px;border:1px solid rgba(168,139,250,.25);border-radius:18px;background:rgba(124,58,237,.09);margin-bottom:14px}.v102-edital-hero>span{font-size:30px}.v102-edital-hero p{margin:4px 0 0;opacity:.7;font-size:13px}.v102-edital-stats{display:grid;grid-template-columns:1fr 1fr;gap:9px;margin:12px 0 14px}.v102-edital-stats article{padding:13px;border:1px solid rgba(255,255,255,.08);border-radius:15px;background:#0d1420}.v102-edital-stats strong{display:block;font-size:22px}.v102-edital-stats small{font-size:10px;opacity:.6}.v102-edital-bar{grid-column:1/-1;height:7px;background:rgba(255,255,255,.08);border-radius:20px;overflow:hidden}.v102-edital-bar i{display:block;height:100%;background:linear-gradient(90deg,#7c3aed,#a78bfa);border-radius:20px}.v102-edital-filters{display:grid;grid-template-columns:1fr 1fr;gap:8px;margin-bottom:15px}.v102-edital-filters select{min-width:0;padding:12px 9px;border-radius:12px;background:#101827;color:#fff;border:1px solid rgba(255,255,255,.1)}.v102-edital-group{margin:0 0 16px}.v102-edital-title{display:flex;gap:10px;align-items:center;margin:0 0 9px}.v102-edital-title>span{font-size:24px}.v102-edital-title h3{margin:0;font-size:15px}.v102-edital-title small{opacity:.55}.v102-topic{width:100%;text-align:left;display:flex;align-items:center;justify-content:space-between;gap:10px;padding:13px;margin:7px 0;border-radius:13px;background:#0c131f;color:#eef2ff;border:1px solid rgba(255,255,255,.07)}.v102-topic span{font-size:13px;line-height:1.35}.v102-topic b{font-size:10px;white-space:nowrap;opacity:.72}.v102-topic.s1{border-color:rgba(250,204,21,.35);background:rgba(250,204,21,.05)}.v102-topic.s2{border-color:rgba(34,197,94,.35);background:rgba(34,197,94,.06)}.v102-topic.s2 b{color:#86efac;opacity:1}.v102-edital-note{font-size:11px;line-height:1.5;opacity:.55;padding:12px 4px 25px}@media(max-width:380px){.v102-edital-filters{grid-template-columns:1fr}.v102-topic{align-items:flex-start;flex-direction:column}.v102-topic b{align-self:flex-end}}
`;document.head.appendChild(css);
})();
