/* Missão PMMG V6.3.9 — Conteúdo real baseado no Anexo B do Edital DRH/CRS nº 10/2024 (CFSd QP-PM/2025). */
window.lessons = {
1:{title:'Interpretação e estudo de texto',subtitle:'Português • Aula 01 • Edital 1.4',time:'35 min',content:`
<div class="edital-badge">📋 EDITAL PMMG • 1.4 ESTUDO DE TEXTO</div>
<h3>O que a prova quer de você</h3><p>Interpretar é responder com base no que o texto permite concluir. Em questões com comandos como <b>“segundo o texto”</b>, sua opinião pessoal não é a referência: a resposta precisa estar sustentada pelo texto.</p>
<h3>Informação explícita x implícita</h3><p><b>Explícita</b> é a informação escrita diretamente. <b>Implícita</b> é uma conclusão autorizada por pistas do texto. Inferir não é inventar: é ligar pistas.</p>
<div class="lesson-example"><b>Exemplo:</b> “Rafael fechou as janelas e, minutos depois, ouviu trovões.” É razoável inferir que havia sinais de chuva; não é possível afirmar que Rafael tem medo de trovões.</div>
<h3>Tema, assunto e finalidade</h3><p>O <b>assunto</b> é o campo geral; o <b>tema</b> é o recorte tratado; a <b>finalidade</b> é o que o autor pretende fazer: informar, convencer, orientar, criticar, narrar etc.</p>
<div class="gold-rule">🎯 REGRA DE OURO: volte ao trecho e procure a prova textual da alternativa.</div>
<div class="video-lesson"><span>🎥 VIDEOAULA RECOMENDADA</span><h3>Português para PMMG — visão geral</h3><p>Aula direcionada ao concurso PMMG.</p><iframe src="https://www.youtube.com/embed/wO8eyBE9lIo" title="Português PMMG" allowfullscreen loading="lazy"></iframe></div>`,quiz:[
{question:'Em uma questão que pergunta “Segundo o texto...”, qual deve ser a principal referência?',options:['A experiência pessoal do candidato.','As informações apresentadas pelo texto.','A alternativa mais longa.','Aquilo que normalmente ocorre na vida real.'],answer:1,explanation:'O comando limita a resposta ao conteúdo textual.',tip:'Procure evidência no próprio texto.'},
{question:'Informação implícita é aquela que:',options:['Aparece obrigatoriamente no título.','Não tem relação com o texto.','Pode ser concluída a partir de pistas do texto.','É copiada literalmente.'],answer:2,explanation:'A inferência nasce de pistas presentes no texto.',tip:'Implícito = não escrito diretamente, mas sustentado.'},
{question:'Se um texto apresenta benefícios da atividade física e riscos do sedentarismo, um tema adequado é:',options:['Atividade física e saúde.','História das Olimpíadas.','Construção de academias.','Vegetarianismo.'],answer:0,explanation:'O tema resume o núcleo comum das ideias desenvolvidas.',tip:'Escolha a alternativa que abrange o texto sem fugir dele.'},
{question:'A finalidade de um texto instrucional costuma ser:',options:['Narrar uma aventura.','Orientar como realizar algo.','Criar suspense.','Descrever apenas sentimentos.'],answer:1,explanation:'Textos instrucionais orientam procedimentos.',tip:'Pergunte: o autor quer que o leitor faça o quê?'},
{question:'Uma inferência válida deve:',options:['Ser baseada apenas na opinião do leitor.','Contradizer o texto.','Ser sustentada por elementos do texto.','Adicionar fatos sem pistas.'],answer:2,explanation:'Inferências precisam ser autorizadas pelo texto.',tip:'Sem pista textual, é suposição.'},
{question:'O assunto de um texto é:',options:['O campo geral de que ele trata.','Sempre a primeira frase.','A opinião do leitor.','Somente o título.'],answer:0,explanation:'Assunto é a área geral; tema é um recorte mais específico.',tip:'Pense no “sobre o que” em sentido amplo.'}
]},
2:{title:'Ideia principal, inferência e argumentação',subtitle:'Português • Aula 02 • Edital 1.2 e 1.4',time:'40 min',content:`
<div class="edital-badge">📋 EDITAL PMMG • 1.2 ARGUMENTOS + 1.4 ESTUDO DE TEXTO</div>
<h3>Ideia principal</h3><p>A ideia principal é a mensagem central que organiza as demais informações. Detalhes, exemplos e dados servem para desenvolver ou sustentar essa ideia.</p>
<h3>Tese e argumento</h3><p>Em texto argumentativo, a <b>tese</b> é o ponto de vista defendido. <b>Argumentos</b> são razões, dados, exemplos ou relações lógicas usados para sustentá-la.</p>
<h3>Pertinência e relevância</h3><p>Um argumento é pertinente quando se relaciona diretamente à tese. É relevante quando contribui de modo importante para sustentá-la.</p>
<div class="lesson-example"><b>Exemplo:</b> tese: “A leitura diária deve ser estimulada.” Um dado sobre ampliação de vocabulário é pertinente; a cor da capa de um livro, em regra, não é.</div>
<div class="gold-rule">🎯 REGRA DE OURO: se retirar um detalhe e a mensagem central continuar intacta, provavelmente era informação secundária.</div>
<div class="video-lesson"><span>🎥 VIDEOAULA • INFERÊNCIA E INTERPRETAÇÃO</span><h3>Compreensão e interpretação de textos para concursos</h3><p>Aula de apoio com inferências, contexto e compreensão textual.</p><iframe src="https://www.youtube.com/embed/ptbiYTNF_i4" title="Inferência e interpretação de textos" allowfullscreen loading="lazy"></iframe></div>`,quiz:[
{question:'Em um texto argumentativo, tese é:',options:['Um exemplo sem relação com o tema.','O ponto de vista central defendido.','Qualquer palavra repetida.','A assinatura do autor.'],answer:1,explanation:'A tese é a posição central que os argumentos procuram sustentar.',tip:'Procure o que o autor quer que o leitor aceite.'},
{question:'Um argumento pertinente é aquele que:',options:['Tem relação direta com a tese.','É sempre longo.','Usa palavras difíceis.','Aparece no último parágrafo.'],answer:0,explanation:'Pertinência significa adequação ao ponto discutido.',tip:'Pergunte se o argumento ajuda a defender a tese.'},
{question:'A ideia principal de um parágrafo corresponde:',options:['Ao detalhe menos importante.','À mensagem central desenvolvida.','Somente à primeira palavra.','A uma informação externa.'],answer:1,explanation:'Ela sintetiza o núcleo informacional do parágrafo.',tip:'Resuma o parágrafo em uma frase.'},
{question:'Dados estatísticos podem funcionar como:',options:['Argumentos de sustentação.','Pontuação.','Título obrigatório.','Erro de coerência.'],answer:0,explanation:'Dados podem servir de evidência para uma tese.',tip:'Evidência fortalece argumento.'},
{question:'Inferir significa:',options:['Copiar literalmente.','Concluir a partir de pistas.','Ignorar o texto.','Trocar o tema.'],answer:1,explanation:'Inferência é conclusão sustentada por indícios.',tip:'Pista + raciocínio = inferência.'},
{question:'Qual elemento costuma ser secundário?',options:['A tese do texto.','Um exemplo usado para ilustrar a tese.','A ideia central.','A conclusão principal.'],answer:1,explanation:'Exemplos normalmente desenvolvem uma ideia maior.',tip:'Diferencie núcleo de apoio.'}
]},
3:{title:'Seleção vocabular e sentido das palavras',subtitle:'Português • Aula 03 • Edital 1.3 e 1.25',time:'35 min',content:`
<div class="edital-badge">📋 EDITAL PMMG • 1.3 SELEÇÃO VOCABULAR + 1.25 SEMÂNTICA</div>
<h3>Palavra certa no contexto</h3><p>Seleção vocabular é a escolha de palavras adequadas ao sentido, ao nível de formalidade e à intenção comunicativa. A banca pode trocar uma palavra e perguntar se o sentido foi mantido.</p>
<h3>Denotação e conotação</h3><p><b>Denotação</b>: sentido literal. <b>Conotação</b>: sentido figurado. Em “o policial manteve a cabeça fria”, não se fala de temperatura, mas de autocontrole.</p>
<h3>Sinônimos e contexto</h3><p>Palavras próximas nem sempre são intercambiáveis em qualquer frase. O contexto decide.</p>
<div class="gold-rule">🎯 REGRA DE OURO: nunca avalie uma palavra isoladamente quando a questão pede sentido no texto.</div>
<div class="video-lesson"><span>🔥 VIDEOAULA POPULAR • +500 MIL VISUALIZAÇÕES</span><h3>Semântica — sentido das palavras</h3><p>Denotação, conotação, sinonímia, polissemia e outros pontos importantes para concursos.</p><iframe src="https://www.youtube.com/embed/P5DTDKxMCp0" title="Semântica e sentido das palavras" allowfullscreen loading="lazy"></iframe></div>`,quiz:[
{question:'Em “ele manteve a cabeça fria durante a ocorrência”, a expressão está em sentido:',options:['Literal.','Conotativo.','Técnico matemático.','Sem sentido.'],answer:1,explanation:'“Cabeça fria” indica calma/autocontrole.',tip:'Conotação = sentido figurado.'},
{question:'A escolha vocabular adequada deve considerar:',options:['Apenas o tamanho da palavra.','Contexto e intenção comunicativa.','Somente a letra inicial.','A preferência pessoal do leitor.'],answer:1,explanation:'Vocabulário precisa se ajustar ao contexto e objetivo.',tip:'Contexto governa sentido.'},
{question:'Denotação corresponde ao sentido:',options:['Figurado.','Literal.','Irônico obrigatoriamente.','Ambíguo obrigatoriamente.'],answer:1,explanation:'Denotação é o sentido básico/literal.',tip:'Dicionário lembra denotação.'},
{question:'Sinônimos:',options:['São sempre substituíveis sem alterar nada.','Podem variar de adequação conforme o contexto.','Nunca têm sentidos próximos.','São apenas verbos.'],answer:1,explanation:'A equivalência depende do uso concreto.',tip:'Teste a troca na frase.'},
{question:'Uma palavra com mais de um sentido apresenta:',options:['Polissemia.','Pontuação.','Concordância.','Acentuação.'],answer:0,explanation:'Polissemia é multiplicidade de sentidos relacionados.',tip:'Poli = muitos.'},
{question:'Em prova, para determinar o sentido de uma palavra, é mais seguro:',options:['Ignorar a frase.','Ler o contexto em que aparece.','Escolher o significado mais raro.','Usar apenas a memória do dicionário.'],answer:1,explanation:'O contexto seleciona o sentido efetivo.',tip:'Leia antes e depois da palavra.'}
]},
4:{title:'Tipologia e gêneros textuais',subtitle:'Português • Aula 04 • Edital 1.5',time:'40 min',content:`
<div class="edital-badge">📋 EDITAL PMMG • 1.5 TIPOLOGIA TEXTUAL E GÊNEROS TEXTUAIS</div>
<h3>Tipo textual x gênero</h3><p><b>Tipo textual</b> é uma estrutura predominante: narração, descrição, exposição, argumentação e injunção. <b>Gênero textual</b> é uma forma concreta de comunicação: notícia, edital, receita, artigo de opinião, e-mail, relatório etc.</p>
<h3>Como reconhecer</h3><p>Narração apresenta acontecimentos; descrição caracteriza; exposição explica; argumentação defende ponto de vista; injunção orienta ações.</p>
<div class="lesson-example"><b>Exemplo:</b> uma receita é gênero textual e apresenta forte sequência injuntiva, pois orienta ações.</div>
<div class="gold-rule">🎯 REGRA DE OURO: gênero é “o texto que circula”; tipo é “a estrutura linguística que predomina”.</div>
<div class="video-lesson"><span>🔥 VIDEOAULA POPULAR • TIPOS E GÊNEROS TEXTUAIS</span><h3>Tipos e gêneros textuais — Português com Letícia</h3><p>Aula completa sobre tipos textuais, gêneros textuais e como diferenciá-los em questões.</p><iframe src="https://www.youtube.com/embed/keri15mSleA" title="Tipos e gêneros textuais" allowfullscreen loading="lazy"></iframe></div>`,quiz:[
{question:'Notícia, receita e artigo de opinião são exemplos de:',options:['Gêneros textuais.','Classes gramaticais.','Fonemas.','Orações subordinadas.'],answer:0,explanation:'São formas concretas de textos em situações sociais.',tip:'Gênero = formato social do texto.'},
{question:'O tipo textual que orienta procedimentos é:',options:['Descritivo.','Injuntivo.','Narrativo.','Lírico.'],answer:1,explanation:'Injunção orienta, ordena ou instrui.',tip:'Manual e receita lembram injunção.'},
{question:'Uma sequência que apresenta fatos em ordem temporal tende a ser:',options:['Narrativa.','Descritiva.','Injuntiva.','Apenas expositiva.'],answer:0,explanation:'Narração organiza acontecimentos.',tip:'Ação + tempo = pista de narração.'},
{question:'Um texto que defende uma tese é predominantemente:',options:['Argumentativo.','Descritivo.','Injuntivo.','Enumerativo sem função.'],answer:0,explanation:'Argumentação busca sustentar um ponto de vista.',tip:'Tese + argumentos.'},
{question:'Descrição tem como foco principal:',options:['Caracterizar seres, objetos, lugares ou situações.','Dar ordens.','Defender sempre uma tese.','Apresentar apenas diálogos.'],answer:0,explanation:'A descrição constrói características.',tip:'Pergunte “como é?”.'},
{question:'Um mesmo gênero textual:',options:['Pode combinar diferentes tipos textuais.','Só pode ter um tipo textual.','Não possui finalidade.','Nunca muda conforme contexto.'],answer:0,explanation:'Gêneros frequentemente misturam sequências tipológicas.',tip:'Predominância não significa exclusividade.'}
]},
5:{title:'Ortografia oficial',subtitle:'Português • Aula 05 • Edital 1.6',time:'40 min',content:`
<div class="edital-badge">📋 EDITAL PMMG • 1.6 ORTOGRAFIA OFICIAL</div>
<h3>Onde a banca costuma apertar</h3><p>Ortografia envolve grafia correta, emprego de letras, hífen e pares que geram dúvida. Para concurso, vale estudar o padrão oficial e revisar erros recorrentes.</p>
<h3>Por que / porque / por quê / porquê</h3><p><b>por que</b> em perguntas ou equivalente a “pelo qual”; <b>porque</b> em explicações/respostas; <b>por quê</b> no fim de enunciado; <b>porquê</b> como substantivo.</p>
<h3>Há x a</h3><p><b>Há</b> indica tempo passado ou existência. <b>A</b> pode indicar tempo futuro ou distância.</p>
<div class="gold-rule">🎯 REGRA DE OURO: transforme a regra em contraste e treine em frases, não em listas soltas.</div>
<div class="video-lesson"><span>🎥 VIDEOAULA • ORTOGRAFIA PARA CONCURSOS</span><h3>Ortografia oficial — hífen, porquês e novo acordo</h3><p>Reforço direcionado aos pontos mais cobrados em concursos.</p><iframe src="https://www.youtube.com/embed/39XGB8KKmBs" title="Ortografia oficial para concursos" allowfullscreen loading="lazy"></iframe></div>`,quiz:[
{question:'Assinale a forma adequada: “Não sei ___ ele faltou.”',options:['porque','por que','porquê','por quê'],answer:1,explanation:'Em pergunta indireta, usa-se “por que”.',tip:'Equivale a “por qual motivo”.'},
{question:'Assinale: “Ele faltou ___ estava doente.”',options:['por que','porque','por quê','porquê'],answer:1,explanation:'“Porque” introduz explicação/causa.',tip:'Resposta → porque.'},
{question:'Assinale: “Você saiu mais cedo ___?”',options:['porque','porquê','por que','por quê'],answer:3,explanation:'No fim da pergunta, usa-se “por quê”.',tip:'Antes da pontuação, o quê recebe acento.'},
{question:'Assinale: “Ninguém explicou o ___ da mudança.”',options:['por que','porque','porquê','por quê'],answer:2,explanation:'Com artigo “o”, funciona como substantivo.',tip:'O porquê = o motivo.'},
{question:'Em “Cheguei aqui há duas horas”, “há” indica:',options:['Tempo passado.','Tempo futuro.','Distância futura.','Condição.'],answer:0,explanation:'O verbo haver marca tempo decorrido.',tip:'Há = faz, quando indica passado.'},
{question:'Em “A prova será daqui a dois meses”, usa-se “a” porque indica:',options:['Tempo futuro.','Tempo passado.','Existência.','Causa.'],answer:0,explanation:'Para intervalo futuro, emprega-se “a”.',tip:'Daqui a...' }
]},
6:{title:'Acentuação gráfica',subtitle:'Português • Aula 06 • Edital 1.7',time:'45 min',content:`
<div class="edital-badge">📋 EDITAL PMMG • 1.7 ACENTUAÇÃO GRÁFICA</div>
<h3>Comece pela sílaba tônica</h3><p><b>Oxítona</b>: última sílaba tônica. <b>Paroxítona</b>: penúltima. <b>Proparoxítona</b>: antepenúltima — e toda proparoxítona é acentuada.</p>
<h3>Regras muito cobradas</h3><p>Oxítonas terminadas em <b>a(s), e(s), o(s), em, ens</b> são acentuadas. Paroxítonas seguem terminações específicas. Hiatos com <b>i/u</b> tônicos exigem atenção às condições da regra.</p>
<div class="gold-rule">🎯 REGRA DE OURO: classifique a tonicidade antes de decidir a regra.</div>
<div class="video-lesson"><span>🔥 VIDEOAULA POPULAR • +1,3 MI VISUALIZAÇÕES NA BUSCA</span><h3>Acentuação gráfica — Português sem Enrolação</h3><p>Revisão ampla para concursos e vestibulares.</p><iframe src="https://www.youtube.com/embed/Ytw1SjnqEJ8" title="Acentuação gráfica" allowfullscreen loading="lazy"></iframe></div>`,quiz:[
{question:'Toda palavra proparoxítona:',options:['É acentuada.','Nunca é acentuada.','Só é acentuada se terminar em a.','Só aparece no plural.'],answer:0,explanation:'Todas as proparoxítonas recebem acento gráfico.',tip:'É a regra mais direta.'},
{question:'A palavra “café” é:',options:['Oxítona.','Paroxítona.','Proparoxítona.','Átona.'],answer:0,explanation:'A sílaba tônica é a última: fé.',tip:'Pronuncie e localize a força.'},
{question:'A palavra “médico” é:',options:['Oxítona.','Paroxítona.','Proparoxítona.','Monossílaba.'],answer:2,explanation:'Mé-di-co: tonicidade na antepenúltima.',tip:'Toda proparoxítona é acentuada.'},
{question:'A palavra “também” recebe acento por ser:',options:['Oxítona terminada em em.','Proparoxítona.','Paroxítona terminada em a.','Monossílaba átona.'],answer:0,explanation:'É oxítona terminada em “em”.',tip:'Observe a terminação.'},
{question:'Para aplicar regras de acentuação, primeiro é útil identificar:',options:['A sílaba tônica.','O número de letras apenas.','O autor do texto.','A pontuação anterior.'],answer:0,explanation:'A posição da sílaba tônica orienta a classificação.',tip:'Tonicidade primeiro.'},
{question:'Qual palavra é proparoxítona?',options:['Café.','Também.','Lâmpada.','Papel.'],answer:2,explanation:'Lâm-pa-da tem tonicidade na antepenúltima.',tip:'Conte as sílabas a partir do fim.'}
]},
7:{title:'Pontuação',subtitle:'Português • Aula 07 • Edital 1.8',time:'45 min',content:`
<div class="edital-badge">📋 EDITAL PMMG • 1.8 EMPREGO DOS SINAIS DE PONTUAÇÃO</div>
<h3>Vírgula não é “pausa para respirar”</h3><p>A vírgula marca relações sintáticas. Entre usos frequentes: separar itens de enumeração, vocativo, aposto, adjuntos deslocados e certas orações.</p>
<h3>Erro clássico</h3><p>Em regra, não se separa <b>sujeito do verbo</b> nem <b>verbo de seu complemento</b> apenas com uma vírgula.</p>
<div class="lesson-example"><b>Exemplo:</b> “Os candidatos atentos resolveram a questão.” Não cabe vírgula entre “candidatos” e “resolveram”.</div>
<h3>Dois-pontos e ponto e vírgula</h3><p>Dois-pontos podem introduzir explicação, enumeração ou fala. O ponto e vírgula pode separar estruturas coordenadas mais extensas.</p>
<div class="gold-rule">🎯 REGRA DE OURO: antes de pôr vírgula, identifique a função sintática dos termos.</div>
<div class="video-lesson"><span>🎥 VIDEOAULA • PONTUAÇÃO PARA CONCURSOS</span><h3>Pontuação — vírgula, ponto e vírgula, dois-pontos e travessão</h3><p>Aula direcionada aos principais usos de pontuação cobrados em concursos.</p><iframe src="https://www.youtube.com/embed/K9PRjM8POy0" title="Pontuação para concursos" allowfullscreen loading="lazy"></iframe></div>`,quiz:[
{question:'Em regra, a vírgula NÃO deve separar:',options:['Itens de uma enumeração.','Vocativo.','Sujeito e verbo.','Aposto explicativo.'],answer:2,explanation:'Sujeito e predicado mantêm ligação sintática direta.',tip:'Não corte a estrutura básica sujeito + verbo.'},
{question:'Em “João, venha aqui”, a vírgula separa:',options:['Vocativo.','Sujeito do verbo.','Objeto direto.','Predicativo.'],answer:0,explanation:'“João” é chamamento, portanto vocativo.',tip:'Chamou alguém? Pense em vocativo.'},
{question:'Os dois-pontos podem introduzir:',options:['Uma enumeração.','Somente uma pergunta.','Acentuação.','Concordância nominal.'],answer:0,explanation:'É um de seus usos frequentes.',tip:'Anúncio → explicação/lista.'},
{question:'Em uma enumeração simples, os itens podem ser separados por:',options:['Vírgulas.','Acentos circunflexos.','Hífens obrigatoriamente.','Apóstrofos.'],answer:0,explanation:'A vírgula é comum na separação de itens coordenados.',tip:'Lista simples = vírgulas.'},
{question:'A pontuação pode:',options:['Alterar relações de sentido.','Ser ignorada sem efeito.','Substituir toda concordância.','Eliminar a necessidade de contexto.'],answer:0,explanation:'Mudanças de pontuação podem alterar organização e sentido.',tip:'Pontuação também constrói sentido.'},
{question:'A vírgula entre verbo e complemento, sem elemento intercalado, é em regra:',options:['Inadequada.','Obrigatória.','Sempre opcional.','Exigida em qualquer frase longa.'],answer:0,explanation:'Não se rompe a ligação verbo-complemento sem motivo sintático.',tip:'Evite vírgula só porque a frase ficou longa.'}
]},
8:{title:'Estrutura e formação de palavras',subtitle:'Português • Aula 08 • Edital 1.9',time:'45 min',content:`
<div class="edital-badge">📋 EDITAL PMMG • 1.9 ESTRUTURA E FORMAÇÃO DE PALAVRAS</div>
<h3>Elementos mórficos</h3><p><b>Radical</b> concentra o núcleo de sentido; afixos podem ser prefixos ou sufixos. Desinências marcam flexões; vogal temática participa da estrutura de certas palavras.</p>
<h3>Derivação</h3><p>Há derivação prefixal, sufixal, prefixal e sufixal, parassintética, regressiva e imprópria. A prova costuma exigir reconhecimento do processo.</p>
<h3>Composição</h3><p>Na composição por <b>justaposição</b>, os elementos mantêm sua forma perceptível; na <b>aglutinação</b>, ocorre alteração fonética/gráfica na união.</p>
<div class="gold-rule">🎯 REGRA DE OURO: compare a palavra formada com sua base e observe o que foi acrescentado ou alterado.</div>
<div class="video-lesson"><span>🎥 VIDEOAULA PMMG</span><h3>Morfologia — PMMG 2025</h3><p>Aula específica para o concurso da PMMG.</p><iframe src="https://www.youtube.com/embed/7csC8xrdGks" title="Morfologia PMMG" allowfullscreen loading="lazy"></iframe></div>`,quiz:[
{question:'O elemento que concentra o núcleo de sentido da palavra é o:',options:['Radical.','Ponto final.','Artigo.','Acento.'],answer:0,explanation:'O radical é a base lexical comum a palavras da mesma família.',tip:'Pedra, pedreiro, pedregulho → pedr-.'},
{question:'Em “infeliz”, “in-” funciona como:',options:['Prefixo.','Sufixo.','Desinência verbal.','Artigo.'],answer:0,explanation:'O elemento é acrescentado antes da base “feliz”.',tip:'Antes = prefixo.'},
{question:'Em “felizmente”, “-mente” é:',options:['Prefixo.','Sufixo.','Radical.','Preposição.'],answer:1,explanation:'É elemento acrescentado depois da base.',tip:'Depois = sufixo.'},
{question:'A união de dois radicais para formar uma palavra caracteriza:',options:['Composição.','Pontuação.','Concordância.','Acentuação.'],answer:0,explanation:'Composição combina bases/radicais.',tip:'Duas bases → composição.'},
{question:'Na justaposição:',options:['Os elementos permanecem reconhecíveis.','Sempre desaparecem os dois radicais.','Há obrigatoriamente acento grave.','Só existem verbos.'],answer:0,explanation:'A justaposição une elementos sem perda estrutural relevante.',tip:'Justa + posição: lado a lado.'},
{question:'Derivação sufixal ocorre quando:',options:['Acrescenta-se elemento depois da base.','Retira-se toda a palavra.','Une-se apenas pontuação.','Acrescenta-se artigo antes do substantivo.'],answer:0,explanation:'Sufixo é afixo posposto à base.',tip:'Sufixo vem no fim.'}
]},
9:{title:'Classes de palavras',subtitle:'Português • Aula 09 • Edital 1.10',time:'50 min',content:`
<div class="edital-badge">📋 EDITAL PMMG • CLASSES DE PALAVRAS</div>
<h3>As 10 classes gramaticais</h3><p>As palavras são agrupadas conforme seu comportamento e função: <b>substantivo, artigo, adjetivo, numeral, pronome, verbo, advérbio, preposição, conjunção e interjeição</b>.</p>
<h3>Variáveis x invariáveis</h3><p>Substantivos, artigos, adjetivos, numerais, pronomes e verbos podem sofrer flexões. Advérbios, preposições, conjunções e interjeições são, em regra, invariáveis.</p>
<div class="lesson-example"><b>Exemplo:</b> em “Os candidatos atentos estudaram muito”, “candidatos” é substantivo, “atentos” é adjetivo, “estudaram” é verbo e “muito” funciona como advérbio.</div>
<div class="gold-rule">🎯 REGRA DE OURO: classifique a palavra dentro da frase; a mesma forma pode exercer funções diferentes conforme o contexto.</div>
<div class="video-lesson"><span>🔥 VIDEOAULA POPULAR • +120 MIL VISUALIZAÇÕES</span><h3>Classes de palavras — Português para Concursos</h3><p>Mapa das 10 classes gramaticais e distinção entre variáveis e invariáveis.</p><iframe src="https://www.youtube.com/embed/MVsC4iP1FvA" title="Classes de palavras para concursos" allowfullscreen loading="lazy"></iframe></div>`,quiz:[
{question:'Qual alternativa apresenta apenas classes invariáveis?',options:['Advérbio, preposição e conjunção.','Substantivo, artigo e adjetivo.','Pronome, verbo e numeral.','Adjetivo, advérbio e artigo.'],answer:0,explanation:'Advérbio, preposição e conjunção são classes invariáveis.',tip:'Comece separando variáveis de invariáveis.'},
{question:'Em “candidato dedicado”, a palavra “dedicado” é:',options:['Adjetivo.','Preposição.','Artigo.','Conjunção.'],answer:0,explanation:'Caracteriza o substantivo “candidato”.',tip:'Característica do nome → adjetivo.'},
{question:'A classe que normalmente indica ação, estado ou fenômeno é:',options:['Verbo.','Artigo.','Preposição.','Interjeição.'],answer:0,explanation:'O verbo expressa processo, ação, estado ou fenômeno.',tip:'Procure a palavra que se flexiona em tempo e pessoa.'},
{question:'Em “estudou muito”, “muito” modifica o verbo e funciona como:',options:['Advérbio.','Substantivo.','Artigo.','Pronome.'],answer:0,explanation:'Nesse contexto intensifica a ação verbal.',tip:'A função depende do contexto.'},
{question:'Preposições servem principalmente para:',options:['Relacionar termos.','Nomear seres.','Expressar ação.','Substituir sempre substantivos.'],answer:0,explanation:'A preposição estabelece relações entre termos.',tip:'de, em, com, para são exemplos frequentes.'},
{question:'Conjunções atuam ligando:',options:['Orações ou termos de mesma função.','Somente substantivos próprios.','Apenas números.','Somente verbos no infinitivo.'],answer:0,explanation:'Conjunções conectam termos e orações.',tip:'Observe a relação lógica criada.'}
]},
10:{title:'Sintaxe da oração e do período',subtitle:'Português • Aula 10 • Edital • Sintaxe',time:'55 min',content:`
<div class="edital-badge">📋 EDITAL PMMG • SINTAXE</div>
<h3>Termos essenciais</h3><p>A oração se organiza em torno do <b>verbo</b>. Sujeito é o termo sobre o qual se declara algo; predicado é aquilo que se declara do sujeito. Há também objetos, complementos, adjuntos, aposto e vocativo.</p>
<h3>Período simples e composto</h3><p>Período simples possui uma oração; período composto possui duas ou mais. As orações podem se relacionar por coordenação ou subordinação.</p>
<div class="lesson-example"><b>Exemplo:</b> “Os candidatos resolveram a prova.” Sujeito: “Os candidatos”; núcleo: “candidatos”; predicado: “resolveram a prova”.</div>
<div class="gold-rule">🎯 REGRA DE OURO: encontre primeiro o verbo; depois pergunte quem pratica/sofre o processo e quais termos completam seu sentido.</div>
<div class="video-lesson"><span>🎥 VIDEOAULA • SINTAXE PARA CONCURSOS</span><h3>Sintaxe — oração, sujeito e predicado</h3><p>Use esta aula como reforço para identificar a estrutura da oração antes de resolver as questões.</p><iframe src="https://www.youtube.com/embed/Xz7FzmxA4pk" title="Sintaxe para concursos" allowfullscreen loading="lazy"></iframe></div>`,quiz:[
{question:'Em “Os candidatos estudaram”, o sujeito é:',options:['Os candidatos.','Estudaram.','Oculto obrigatoriamente.','Inexistente.'],answer:0,explanation:'É o termo de que se declara a ação de estudar.',tip:'Pergunte: quem estudou?'},
{question:'Uma oração organiza-se em torno de:',options:['Um verbo ou locução verbal.','Uma vírgula.','Um artigo.','Um adjetivo obrigatoriamente.'],answer:0,explanation:'O verbo é o núcleo estrutural da oração.',tip:'Conte verbos/locuções para começar a analisar.'},
{question:'Período composto possui:',options:['Duas ou mais orações.','Nenhum verbo.','Somente um substantivo.','Obrigatoriamente três parágrafos.'],answer:0,explanation:'Há mais de uma oração.',tip:'Mais de uma estrutura verbal.'},
{question:'O termo que completa o sentido de um verbo transitivo pode ser:',options:['Objeto.','Vocativo apenas.','Artigo.','Interjeição.'],answer:0,explanation:'Objetos direto e indireto completam verbos transitivos.',tip:'Pergunte o quê? quem? de quê? a quem?'},
{question:'Vocativo é usado para:',options:['Chamar ou interpelar alguém.','Completar verbo transitivo.','Indicar sujeito obrigatoriamente.','Ligar duas orações.'],answer:0,explanation:'Vocativo é termo de chamamento.',tip:'“Soldado, atenção!”'},
{question:'Em “João, candidato dedicado, foi aprovado”, “candidato dedicado” é:',options:['Aposto.','Objeto direto.','Verbo.','Conjunção.'],answer:0,explanation:'Explica/identifica o termo João.',tip:'Aposto explica outro termo nominal.'}
]},
11:{title:'Concordância verbal e nominal',subtitle:'Português • Aula 11 • Edital • Concordância',time:'55 min',content:`
<div class="edital-badge">📋 EDITAL PMMG • CONCORDÂNCIA VERBAL E NOMINAL</div>
<h3>Concordância verbal</h3><p>Como regra geral, o verbo concorda em número e pessoa com o núcleo do sujeito: “Os candidatos <b>estudam</b>”. Casos com sujeito composto, expressões partitivas e verbos impessoais exigem atenção.</p>
<h3>Concordância nominal</h3><p>Artigos, adjetivos, numerais e pronomes adjetivos ajustam-se ao substantivo a que se referem.</p>
<div class="lesson-example"><b>Exemplo:</b> “As duas questões difíceis foram resolvidas.” Os determinantes e adjetivos acompanham o feminino plural de “questões”.</div>
<div class="gold-rule">🎯 REGRA DE OURO: descubra o núcleo antes de concordar; palavras próximas podem tentar enganar você.</div>
<div class="video-lesson"><span>🔥 VIDEOAULA POPULAR • +640 MIL VISUALIZAÇÕES</span><h3>Concordância verbal — Português com Letícia</h3><p>Aula completa para concursos, incluindo sujeito composto e verbos impessoais como haver e fazer.</p><iframe src="https://www.youtube.com/embed/s2T9Ap2J7u0" title="Concordância verbal para concursos" allowfullscreen loading="lazy"></iframe></div>`,quiz:[
{question:'Assinale a concordância adequada:',options:['Os candidatos estudam.','Os candidatos estuda.','Os candidato estudam.','Os candidatos estudas.'],answer:0,explanation:'O sujeito plural exige verbo no plural.',tip:'Ache o núcleo do sujeito.'},
{question:'Na concordância nominal, o adjetivo relaciona-se principalmente ao:',options:['Substantivo a que se refere.','Ponto final.','Verbo impessoal sempre.','Título do texto.'],answer:0,explanation:'O adjetivo concorda com o nome em gênero e número, conforme a estrutura.',tip:'Descubra qual nome o adjetivo caracteriza.'},
{question:'Em “As questões difíceis”, “difíceis” está no plural porque concorda com:',options:['Questões.','As apenas.','Uma palavra oculta.','Nenhum termo.'],answer:0,explanation:'O adjetivo caracteriza “questões”.',tip:'Nome + característica.'},
{question:'O verbo “haver” com sentido de existir é, na norma-padrão:',options:['Impessoal e fica no singular.','Sempre plural.','Adjetivo.','Conjunção.'],answer:0,explanation:'Em “Havia candidatos”, haver = existir e permanece singular.',tip:'Haver = existir → singular.'},
{question:'Assinale a forma padrão:',options:['Havia muitas pessoas.','Haviam muitas pessoas.','Houveram problemas ontem.','Existia muitas pessoas.'],answer:0,explanation:'Haver impessoal fica na 3ª pessoa do singular.',tip:'Não concorde “haver” existencial com o termo seguinte.'},
{question:'A concordância verbal depende, em regra, do:',options:['Núcleo do sujeito.','Número de vírgulas.','Tamanho da frase.','Primeiro substantivo encontrado.'],answer:0,explanation:'É o núcleo do sujeito que orienta a concordância básica.',tip:'Núcleo primeiro.'}
]},
12:{title:'Regência verbal e nominal',subtitle:'Português • Aula 12 • Edital • Regência',time:'55 min',content:`
<div class="edital-badge">📋 EDITAL PMMG • REGÊNCIA VERBAL E NOMINAL</div>
<h3>O que é regência</h3><p>Regência estuda a relação entre um termo regente e seu complemento, especialmente a necessidade ou não de <b>preposição</b>. Verbos como assistir, obedecer, preferir e visar aparecem muito em exercícios de concurso.</p>
<h3>Regência nominal</h3><p>Nomes também podem exigir preposição: “favorável <b>a</b>”, “necessidade <b>de</b>”, “respeito <b>a</b>”.</p>
<div class="lesson-example"><b>Exemplo:</b> na norma-padrão, “obedecer <b>às</b> regras” apresenta preposição exigida pelo verbo.</div>
<div class="gold-rule">🎯 REGRA DE OURO: não decore só a preposição; aprenda o sentido do verbo, porque a regência pode mudar com o significado.</div>
<div class="video-lesson"><span>🔥 VIDEOAULA PARA CONCURSOS • +50 MIL VISUALIZAÇÕES</span><h3>Regência nominal e verbal — exercícios</h3><p>Treino prático com verbos frequentemente cobrados em concursos.</p><iframe src="https://www.youtube.com/embed/oOosGRe5gKo" title="Regência verbal e nominal para concursos" allowfullscreen loading="lazy"></iframe></div>`,quiz:[
{question:'Regência estuda principalmente:',options:['A relação entre termos e seus complementos/preposições.','A posição da sílaba tônica.','Somente ortografia.','A divisão em parágrafos.'],answer:0,explanation:'Regência trata das relações de dependência entre termos.',tip:'Pergunte se o termo exige preposição.'},
{question:'Na norma-padrão, o verbo “obedecer” rege:',options:['Preposição a.','Nenhuma preposição em qualquer caso.','Preposição com apenas.','Preposição por apenas.'],answer:0,explanation:'Obedecer a algo/alguém.',tip:'Obedecer às regras.'},
{question:'Em “necessidade de estudo”, “de” é exigido por:',options:['Necessidade.','Estudo.','Um verbo oculto obrigatoriamente.','Pontuação.'],answer:0,explanation:'É caso de regência nominal.',tip:'Nome também pode reger preposição.'},
{question:'A regência de um verbo pode variar conforme:',options:['Seu sentido no contexto.','A cor da página.','O tamanho da palavra seguinte.','A quantidade de parágrafos.'],answer:0,explanation:'Alguns verbos mudam de regência quando mudam de sentido.',tip:'Sentido + complemento.'},
{question:'“Favorável a mudanças” exemplifica:',options:['Regência nominal.','Acentuação.','Concordância verbal.','Derivação.'],answer:0,explanation:'O adjetivo “favorável” rege a preposição a.',tip:'Termo regente é um nome/adjetivo.'},
{question:'Para resolver questão de regência, é importante identificar:',options:['O termo regente e o sentido empregado.','Somente a última palavra.','A quantidade de vírgulas.','A fonte do texto apenas.'],answer:0,explanation:'Esses elementos determinam a construção adequada.',tip:'Quem rege? Qual sentido?' }
]},
13:{title:'Crase',subtitle:'Português • Aula 13 • Edital • Crase',time:'50 min',content:`
<div class="edital-badge">📋 EDITAL PMMG • CRASE</div>
<h3>O encontro de dois “a”</h3><p>A crase ocorre, em geral, quando a preposição <b>a</b> encontra o artigo feminino <b>a/as</b>. O acento grave <b>à</b> sinaliza essa fusão.</p>
<h3>Teste prático</h3><p>Verifique se o termo anterior exige preposição “a” e se o termo seguinte admite artigo feminino. A troca por palavra masculina pode ajudar: se surgir “ao”, há forte indicação de crase no feminino.</p>
<div class="lesson-example"><b>Exemplo:</b> “Dirigi-me <b>à escola</b>” → “Dirigi-me <b>ao colégio</b>”.</div>
<h3>Casos sem crase</h3><p>Em regra, não há crase antes de verbo, palavra masculina e vários pronomes que não admitem artigo.</p>
<div class="gold-rule">🎯 REGRA DE OURO: crase não é “acento de palavra feminina”; confirme preposição + artigo.</div>
<div class="video-lesson"><span>🎥 VIDEOAULA COM QUESTÕES PMMG</span><h3>Acentuação e crase em provas anteriores da PMMG</h3><p>Resolução direcionada ao concurso de Soldado da PMMG.</p><iframe src="https://www.youtube.com/embed/7HiCTNKmio8" title="Crase e acentuação PMMG" allowfullscreen loading="lazy"></iframe></div>`,quiz:[
{question:'A crase normalmente representa a fusão de:',options:['Preposição a + artigo a/as.','Dois verbos.','Artigo o + preposição de.','Duas vírgulas.'],answer:0,explanation:'Essa é a situação básica representada por à/às.',tip:'a + a = à.'},
{question:'Em “Dirigi-me à escola”, a troca por masculino pode resultar em:',options:['Dirigi-me ao colégio.','Dirigi-me o colégio.','Dirigi-me no colégio obrigatoriamente.','Dirigi-me pelo colégio sempre.'],answer:0,explanation:'O aparecimento de “ao” confirma preposição + artigo.',tip:'Teste do “ao”.'},
{question:'Em regra, antes de verbo:',options:['Não ocorre crase.','A crase é sempre obrigatória.','Usa-se sempre “às”.','O verbo vira substantivo.'],answer:0,explanation:'Verbo não admite artigo feminino nessa estrutura.',tip:'Antes de verbo, geralmente sem crase.'},
{question:'Crase deve ser analisada considerando:',options:['Regência e presença de artigo.','Somente gênero feminino.','Somente número de sílabas.','Pontuação final.'],answer:0,explanation:'É necessário verificar os dois “a”.',tip:'Quem exige “a”? O próximo termo aceita artigo?'},
{question:'Assinale a construção com crase adequada:',options:['Fui à escola.','Começou à estudar.','Entreguei à Pedro.','Andei à pé.'],answer:0,explanation:'“Ir a” + “a escola” produz “à escola”.',tip:'Ao colégio → à escola.'},
{question:'O acento usado para indicar crase é o:',options:['Grave.','Agudo.','Circunflexo.','Til.'],answer:0,explanation:'A crase é marcada pelo acento grave.',tip:'à.'}
]},
14:{title:'Coesão e coerência',subtitle:'Português • Aula 14 • Edital • Coesão e coerência',time:'50 min',content:`
<div class="edital-badge">📋 EDITAL PMMG • COESÃO E COERÊNCIA</div>
<h3>Coesão</h3><p>Coesão é a ligação linguística entre partes do texto. Pronomes, conjunções, substituições lexicais e elipses ajudam a conectar frases e parágrafos.</p>
<h3>Coerência</h3><p>Coerência é a construção de sentido global sem contradições indevidas. Um texto pode ter conectivos e ainda ser incoerente se suas ideias entrarem em conflito.</p>
<h3>Conectivos e relações</h3><p>“porque” pode indicar causa; “portanto”, conclusão; “embora”, concessão; “mas”, oposição. A banca frequentemente pergunta que relação um conector estabelece.</p>
<div class="gold-rule">🎯 REGRA DE OURO: ao trocar um conectivo, confira se a relação lógica original foi preservada.</div>
<div class="video-lesson"><span>🎥 VIDEOAULA • FOCO EM CONCURSOS</span><h3>Coesão e coerência — TecConcursos</h3><p>Aula completa sobre texto coeso e coerente, compreensão, interpretação e análise textual.</p><iframe src="https://www.youtube.com/embed/lsVWqWtuusI" title="Coesão e coerência para concursos" allowfullscreen loading="lazy"></iframe></div>`,quiz:[
{question:'Coesão textual está ligada principalmente:',options:['À conexão linguística entre partes do texto.','À quantidade de páginas.','À caligrafia.','Somente ao título.'],answer:0,explanation:'Recursos coesivos conectam elementos textuais.',tip:'Pense em “costura” do texto.'},
{question:'Coerência diz respeito:',options:['Ao sentido global e à compatibilidade das ideias.','Somente à ortografia.','Apenas ao uso de vírgulas.','À fonte utilizada.'],answer:0,explanation:'Coerência envolve lógica e sentido global.',tip:'As ideias fazem sentido juntas?'},
{question:'O conectivo “portanto” costuma introduzir:',options:['Conclusão.','Causa.','Concessão.','Vocativo.'],answer:0,explanation:'“Portanto” marca conclusão/consequência argumentativa.',tip:'Portanto = logo.'},
{question:'“Embora” normalmente expressa:',options:['Concessão.','Conclusão.','Adição apenas.','Explicação nominal.'],answer:0,explanation:'Introduz uma ideia concessiva.',tip:'Embora = apesar de.'},
{question:'Um pronome que retoma termo anterior contribui para:',options:['Coesão referencial.','Acentuação.','Formação de palavras.','Regência exclusivamente.'],answer:0,explanation:'A retomada evita repetição e conecta partes do texto.',tip:'Retomar = referenciar.'},
{question:'Trocar um conectivo sem analisar seu sentido pode:',options:['Alterar a relação lógica do texto.','Nunca mudar nada.','Corrigir automaticamente a gramática.','Eliminar o sujeito.'],answer:0,explanation:'Conectivos expressam relações semânticas específicas.',tip:'Compare causa, oposição, conclusão, concessão etc.'}
]}
,
15:{title:'Termos da oração',subtitle:'Português • Aula 15 • Edital • Termos da oração',time:'55 min',content:`
<div class="edital-badge">📋 EDITAL PMMG • TERMOS DA ORAÇÃO</div><h3>Essenciais, integrantes e acessórios</h3><p>Depois de localizar o verbo, identifique sujeito e predicado. Em seguida, observe complementos verbais e nominais, agente da passiva, adjuntos, aposto e vocativo.</p><div class="lesson-example"><b>Exemplo:</b> “Os candidatos entregaram os documentos ao fiscal.” Sujeito: “Os candidatos”; objeto direto: “os documentos”; objeto indireto: “ao fiscal”.</div><div class="gold-rule">🎯 REGRA DE OURO: classifique o termo pela função que exerce na oração, não apenas pela posição.</div>
<div class="video-lesson"><span>🎥 VIDEOAULA • SINTAXE</span><h3>Sujeito, predicado e termos da oração</h3><p>Reforço para análise sintática voltada a provas.</p><iframe src="https://www.youtube.com/embed/hHnPoZdYDDY" title="Função sintática" allowfullscreen loading="lazy"></iframe></div>`,quiz:[
{question:'Em “Os candidatos entregaram os documentos”, o sujeito é:',options:['Os candidatos.','Os documentos.','Entregaram.','Oculto.'],answer:0,explanation:'É de quem se declara a ação.',tip:'Pergunte quem entregou.'},{question:'Objeto direto completa verbo:',options:['Sem preposição obrigatória, em regra.','Sempre com preposição a.','Somente impessoal.','Sem sentido.'],answer:0,explanation:'É complemento verbal normalmente sem preposição obrigatória.',tip:'Pergunte o quê/quem.'},{question:'Vocativo serve para:',options:['Chamar ou interpelar.','Completar substantivo.','Indicar objeto direto.','Formar sujeito.'],answer:0,explanation:'É termo de chamamento.',tip:'Soldado, atenção!'},{question:'Aposto normalmente:',options:['Explica ou especifica outro termo.','É sempre verbo.','Substitui pontuação.','É conjunção.'],answer:0,explanation:'O aposto esclarece um termo nominal.',tip:'Veja se há explicação.'},{question:'Adjunto adverbial expressa frequentemente:',options:['Circunstância.','Sujeito.','Artigo.','Objeto direto obrigatório.'],answer:0,explanation:'Pode indicar tempo, lugar, modo etc.',tip:'Circunstância da ação.'},{question:'Para iniciar análise sintática, é útil localizar primeiro:',options:['O verbo.','O título.','A maior palavra.','A última vírgula.'],answer:0,explanation:'O verbo organiza a oração.',tip:'Verbo primeiro.'}]},
16:{title:'Período composto: coordenação e subordinação',subtitle:'Português • Aula 16 • Edital • Período composto',time:'60 min',content:`<div class="edital-badge">📋 EDITAL PMMG • PERÍODO COMPOSTO</div><h3>Coordenação</h3><p>Orações coordenadas têm independência sintática e podem estabelecer adição, oposição, alternância, conclusão ou explicação.</p><h3>Subordinação</h3><p>Orações subordinadas exercem função em relação a outra oração e podem ser substantivas, adjetivas ou adverbiais.</p><div class="lesson-example"><b>Exemplo:</b> “Estudou, mas não descansou.” A conjunção “mas” introduz relação adversativa.</div><div class="gold-rule">🎯 REGRA DE OURO: identifique a relação de sentido criada pelo conectivo.</div><div class="video-lesson"><span>🎥 VIDEOAULA • PERÍODO COMPOSTO</span><h3>Período composto por subordinação</h3><p>Visão clara das principais relações entre orações.</p><iframe src="https://www.youtube.com/embed/u0HDf2FFu0g" title="Período composto" allowfullscreen loading="lazy"></iframe></div>`,quiz:[
{question:'Orações coordenadas são, em regra:',options:['Sintaticamente independentes entre si.','Sempre sem verbo.','Sempre adjetivas.','Idênticas.'],answer:0,explanation:'Coordenação não cria dependência sintática.',tip:'Coordenação = lado a lado.'},{question:'“Mas” costuma introduzir oração coordenada:',options:['Adversativa.','Aditiva.','Conclusiva.','Alternativa.'],answer:0,explanation:'Marca oposição.',tip:'Mas = porém.'},{question:'Orações subordinadas adjetivas normalmente se relacionam a:',options:['Um nome antecedente.','Um número.','Pontuação apenas.','Nenhum termo.'],answer:0,explanation:'Têm valor de adjetivo.',tip:'Caracterizam um nome.'},{question:'“Portanto” costuma indicar:',options:['Conclusão.','Oposição.','Alternância.','Concessão.'],answer:0,explanation:'É conectivo conclusivo.',tip:'Portanto = logo.'},{question:'Uma oração subordinada substantiva exerce função típica de:',options:['Substantivo.','Advérbio apenas.','Pontuação.','Interjeição.'],answer:0,explanation:'Pode ser sujeito, objeto etc.',tip:'Tente substituir por “isso”.'},{question:'Para classificar orações, observe principalmente:',options:['Função e relação de sentido.','Quantidade de letras.','Fonte usada.','Tamanho do parágrafo.'],answer:0,explanation:'Esses critérios orientam a análise.',tip:'Estrutura + sentido.'}]},
17:{title:'Pronomes relativos e funções sintáticas',subtitle:'Português • Aula 17 • Edital • Pronomes relativos',time:'50 min',content:`<div class="edital-badge">📋 EDITAL PMMG • PRONOMES RELATIVOS</div><h3>Retomada e ligação</h3><p>Que, quem, o qual, cujo e onde podem retomar antecedente e introduzir oração subordinada adjetiva. O pronome relativo exerce função sintática dentro da oração que inicia.</p><div class="lesson-example"><b>Exemplo:</b> “A prova que fiz estava difícil.” “que” retoma “prova” e funciona como objeto direto de “fiz”.</div><div class="gold-rule">🎯 REGRA DE OURO: substitua o pronome pelo antecedente dentro da oração para descobrir sua função.</div><div class="video-lesson"><span>🔥 VIDEOAULA POPULAR • +1 MILHÃO</span><h3>Pronomes — Português com Letícia</h3><p>Inclui pronomes relativos e seus usos.</p><iframe src="https://www.youtube.com/embed/4LVbsP4v13c" title="Pronomes" allowfullscreen loading="lazy"></iframe></div>`,quiz:[
{question:'Pronome relativo normalmente:',options:['Retoma um antecedente.','Nunca liga orações.','É sempre verbo.','Não tem função sintática.'],answer:0,explanation:'Ele retoma termo anterior e articula orações.',tip:'Procure o antecedente.'},{question:'Em “o livro que li”, “que” retoma:',options:['O livro.','Li.','Uma palavra oculta.','Nenhum termo.'],answer:0,explanation:'O antecedente é “livro”.',tip:'Que = o livro.'},{question:'“Cujo” normalmente estabelece ideia de:',options:['Posse.','Tempo.','Lugar.','Conclusão.'],answer:0,explanation:'Relaciona possuidor e coisa possuída.',tip:'Cujo = de quem/do qual, sem artigo depois.'},{question:'“Onde” como relativo deve relacionar-se preferencialmente a:',options:['Lugar.','Pessoa.','Tempo verbal.','Adjetivo.'],answer:0,explanation:'Retoma lugar.',tip:'Onde = em que lugar.'},{question:'O pronome relativo exerce:',options:['Função sintática na oração que introduz.','Somente função estética.','Nenhuma função.','Sempre sujeito.'],answer:0,explanation:'A função varia conforme a estrutura.',tip:'Recoloque o antecedente.'},{question:'Orações introduzidas por pronome relativo são tipicamente:',options:['Adjetivas.','Coordenadas conclusivas.','Interjeitivas.','Sem predicado.'],answer:0,explanation:'Caracterizam um antecedente.',tip:'Valor de adjetivo.'}]},
18:{title:'Emprego de nomes e pronomes',subtitle:'Português • Aula 18 • Edital • Nomes e pronomes',time:'50 min',content:`<div class="edital-badge">📋 EDITAL PMMG • NOMES E PRONOMES</div><h3>Referência e concordância</h3><p>Pronomes substituem ou acompanham nomes e precisam manter referência clara. Atenção a pronomes pessoais, demonstrativos, possessivos, indefinidos e de tratamento.</p><div class="lesson-example"><b>Exemplo:</b> “Entre mim e você” é a construção padrão após preposição; “para eu estudar” usa “eu” porque é sujeito do infinitivo.</div><div class="gold-rule">🎯 REGRA DE OURO: descubra a função do pronome antes de escolher a forma.</div><div class="video-lesson"><span>🔥 VIDEOAULA POPULAR</span><h3>Pronomes para concursos</h3><p>Revisão das principais classes pronominais.</p><iframe src="https://www.youtube.com/embed/4LVbsP4v13c" title="Pronomes para concursos" allowfullscreen loading="lazy"></iframe></div>`,quiz:[
{question:'Após preposição, em “entre ___ e você”, a forma padrão é:',options:['mim.','eu.','me.','meu.'],answer:0,explanation:'Após preposição usa-se pronome oblíquo tônico.',tip:'Entre mim e você.'},{question:'Em “para eu estudar”, usa-se “eu” porque funciona como:',options:['Sujeito de estudar.','Objeto direto.','Preposição.','Conjunção.'],answer:0,explanation:'“eu” pratica a ação do infinitivo.',tip:'Quem vai estudar? eu.'},{question:'Pronome demonstrativo pode indicar:',options:['Posição/referência no discurso.','Somente ação.','Apenas número.','Pontuação.'],answer:0,explanation:'Este, esse, aquele situam referências.',tip:'Observe contexto.'},{question:'Pronomes possessivos indicam:',options:['Relação de posse.','Tempo verbal.','Oposição.','Conclusão.'],answer:0,explanation:'Meu, seu, nosso etc.',tip:'Posse.'},{question:'A escolha pronominal deve considerar:',options:['Função sintática e referência.','Somente tamanho da palavra.','Cor do texto.','Número de linhas.'],answer:0,explanation:'A função determina a forma adequada.',tip:'Quem faz? Quem recebe?'},{question:'Pronome pode:',options:['Substituir ou acompanhar um nome.','Ser apenas verbo.','Eliminar sujeito sempre.','Nunca retomar termos.'],answer:0,explanation:'Essa é função típica dos pronomes.',tip:'Nome ↔ pronome.'}]},
19:{title:'Tempos e modos verbais',subtitle:'Português • Aula 19 • Edital • Verbos',time:'55 min',content:`<div class="edital-badge">📋 EDITAL PMMG • TEMPOS E MODOS VERBAIS</div><h3>Indicativo, subjuntivo e imperativo</h3><p>O indicativo tende a apresentar fatos; o subjuntivo, hipóteses, desejos ou possibilidades; o imperativo, ordens, pedidos e orientações. Os tempos verbais também organizam relações temporais no texto.</p><div class="lesson-example"><b>Exemplo:</b> “Se eu estudasse, teria mais segurança.” O pretérito imperfeito do subjuntivo marca hipótese.</div><div class="gold-rule">🎯 REGRA DE OURO: em reescrita, preserve tempo, modo e relação de sentido.</div><div class="video-lesson"><span>🔥 VIDEOAULA POPULAR • +600 MIL</span><h3>Tempos e modos verbais — Português com Letícia</h3><p>Visão geral objetiva dos modos e tempos.</p><iframe src="https://www.youtube.com/embed/WK6WqY3iRU8" title="Tempos e modos verbais" allowfullscreen loading="lazy"></iframe></div>`,quiz:[
{question:'O modo subjuntivo costuma expressar:',options:['Hipótese, desejo ou possibilidade.','Somente certeza absoluta.','Apenas ordem.','Nome de seres.'],answer:0,explanation:'É associado a fatos não apresentados como certos.',tip:'Se, talvez, desejo.'},{question:'O modo imperativo é usado frequentemente para:',options:['Ordens, pedidos e orientações.','Narrar passado apenas.','Nomear pessoas.','Indicar posse.'],answer:0,explanation:'É modo de comando/orientação.',tip:'Faça, estude, atenção.'},{question:'Em “Se eu estudasse”, “estudasse” está no:',options:['Pretérito imperfeito do subjuntivo.','Presente do indicativo.','Imperativo.','Infinitivo.'],answer:0,explanation:'A forma marca hipótese.',tip:'Se eu... -sse.'},{question:'Tempo verbal ajuda a localizar:',options:['A ação no tempo.','Somente o sujeito.','A pontuação.','O gênero textual.'],answer:0,explanation:'Situa presente, passado ou futuro e relações internas.',tip:'Quando ocorre?'},{question:'Em reescritas, alterar o modo verbal pode:',options:['Alterar o sentido.','Nunca alterar nada.','Corrigir ortografia automaticamente.','Eliminar o verbo.'],answer:0,explanation:'Certeza e hipótese podem mudar.',tip:'Compare fato x possibilidade.'},{question:'Indicativo tende a apresentar:',options:['Fatos como reais/certos.','Somente desejos.','Apenas ordens.','Interjeições.'],answer:0,explanation:'É o modo mais associado à factualidade.',tip:'Indicativo = indicação de fato.'}]},
20:{title:'Orações reduzidas',subtitle:'Português • Aula 20 • Edital • Orações reduzidas',time:'50 min',content:`<div class="edital-badge">📋 EDITAL PMMG • ORAÇÕES REDUZIDAS</div><h3>Infinitivo, gerúndio e particípio</h3><p>Orações reduzidas não apresentam conectivo típico e têm verbo em forma nominal. Podem ser desenvolvidas preservando a relação de sentido.</p><div class="lesson-example"><b>Exemplo:</b> “Ao terminar a prova, revise.” pode equivaler a “Quando terminar a prova, revise”.</div><div class="gold-rule">🎯 REGRA DE OURO: desenvolva mentalmente a oração e descubra a relação semântica.</div><div class="video-lesson"><span>🎥 VIDEOAULA • ORAÇÕES REDUZIDAS</span><h3>Orações reduzidas para concursos</h3><p>Reforço sobre infinitivo, gerúndio e particípio.</p><iframe src="https://www.youtube.com/embed/u0HDf2FFu0g" title="Orações reduzidas e subordinação" allowfullscreen loading="lazy"></iframe></div>`,quiz:[
{question:'Oração reduzida apresenta verbo em:',options:['Forma nominal.','Somente indicativo.','Somente imperativo.','Nenhuma forma verbal.'],answer:0,explanation:'Infinitivo, gerúndio ou particípio.',tip:'Formas nominais.'},{question:'São formas nominais do verbo:',options:['Infinitivo, gerúndio e particípio.','Presente, passado e futuro.','Sujeito, objeto e predicado.','Nome, artigo e pronome.'],answer:0,explanation:'Essas três formam orações reduzidas.',tip:'-r, -ndo, particípio.'},{question:'Desenvolver uma oração reduzida exige preservar:',options:['Seu sentido.','A mesma quantidade de palavras.','A mesma pontuação sempre.','O mesmo verbo nominal.'],answer:0,explanation:'A relação semântica deve permanecer.',tip:'Forma muda; sentido não.'},{question:'“Ao estudar, aprendo” pode expressar relação de:',options:['Tempo.','Posse.','Vocativo.','Aposto.'],answer:0,explanation:'Pode equivaler a “quando estudo”.',tip:'Desenvolva a oração.'},{question:'Orações reduzidas geralmente não trazem:',options:['Conectivo introdutor típico.','Verbo.','Sentido.','Relação com outra oração.'],answer:0,explanation:'Essa ausência é característica frequente.',tip:'Reduzida = forma compacta.'},{question:'Para classificar oração reduzida, observe:',options:['Forma nominal e função/sentido.','Número de letras.','Título.','Fonte.'],answer:0,explanation:'Esses elementos determinam a classificação.',tip:'Forma + relação.'}]},
21:{title:'Colocação pronominal',subtitle:'Português • Aula 21 • Edital • Colocação pronominal',time:'50 min',content:`<div class="edital-badge">📋 EDITAL PMMG • COLOCAÇÃO PRONOMINAL</div><h3>Próclise, ênclise e mesóclise</h3><p>Próclise: pronome antes do verbo; ênclise: depois; mesóclise: no meio. Palavras negativas, pronomes relativos e certos advérbios podem atrair o pronome.</p><div class="lesson-example"><b>Exemplo:</b> “Não me diga isso.” A palavra negativa “não” favorece próclise.</div><div class="gold-rule">🎯 REGRA DE OURO: procure primeiro uma palavra atrativa.</div><div class="video-lesson"><span>🎥 VIDEOAULA • QUESTÃO DE CONCURSO</span><h3>Colocação pronominal — Português com Letícia</h3><p>Aplicação em questão de concurso.</p><iframe src="https://www.youtube.com/embed/_aKblqr6xPs" title="Colocação pronominal" allowfullscreen loading="lazy"></iframe></div>`,quiz:[
{question:'Próclise é a colocação do pronome:',options:['Antes do verbo.','Depois do verbo.','No meio do verbo.','Fora da oração.'],answer:0,explanation:'Ex.: “não me diga”.',tip:'Pró = antes.'},{question:'Ênclise coloca o pronome:',options:['Depois do verbo.','Antes do verbo.','No meio do verbo.','Antes do sujeito sempre.'],answer:0,explanation:'Ex.: “diga-me”.',tip:'Ênclise = depois.'},{question:'Mesóclise coloca o pronome:',options:['No interior da forma verbal.','Antes do substantivo.','Depois do ponto.','No sujeito.'],answer:0,explanation:'Ex.: “dir-lhe-ei”.',tip:'Meso = meio.'},{question:'Palavra negativa costuma favorecer:',options:['Próclise.','Ênclise obrigatória.','Mesóclise sempre.','Ausência de pronome.'],answer:0,explanation:'Negação é fator de atração.',tip:'Não me diga.'},{question:'Pronome relativo pode funcionar como:',options:['Fator de próclise.','Sinal de pontuação.','Verbo auxiliar.','Artigo definido.'],answer:0,explanation:'Atrai pronome oblíquo átono.',tip:'Que me disse.'},{question:'Ao resolver colocação pronominal, procure:',options:['Palavra atrativa e contexto verbal.','Somente o tamanho do verbo.','A primeira vírgula.','O título.'],answer:0,explanation:'Esses elementos orientam a posição.',tip:'Atração primeiro.'}]},
22:{title:'Estilística e efeitos de sentido',subtitle:'Português • Aula 22 • Edital • Estilística',time:'45 min',content:`<div class="edital-badge">📋 EDITAL PMMG • ESTILÍSTICA</div><h3>Escolhas expressivas</h3><p>Estilística observa como escolhas de palavras, estruturas, repetições, sonoridade e ordem dos termos produzem efeitos de sentido.</p><div class="lesson-example"><b>Exemplo:</b> repetir uma expressão pode enfatizar uma ideia; inverter a ordem comum pode destacar um termo.</div><div class="gold-rule">🎯 REGRA DE OURO: pergunte qual efeito a escolha linguística produz naquele contexto.</div><div class="video-lesson"><span>🎥 VIDEOAULA • EFEITOS DE SENTIDO</span><h3>Figuras e recursos expressivos</h3><p>Base prática para reconhecer efeitos estilísticos em provas.</p><iframe src="https://www.youtube.com/embed/DZq92F2xg6c" title="Estilística e figuras" allowfullscreen loading="lazy"></iframe></div>`,quiz:[
{question:'Estilística estuda principalmente:',options:['Efeitos expressivos das escolhas linguísticas.','Somente ortografia.','Apenas número de palavras.','Somente classes gramaticais.'],answer:0,explanation:'Analisa efeitos de sentido e expressão.',tip:'Como foi dito e com qual efeito?'},{question:'Repetição pode ser usada para:',options:['Criar ênfase.','Eliminar sentido sempre.','Formar artigo.','Impedir coesão obrigatoriamente.'],answer:0,explanation:'É um recurso expressivo possível.',tip:'Observe intenção.'},{question:'A ordem dos termos pode:',options:['Produzir destaque e efeito de sentido.','Nunca alterar foco.','Eliminar o verbo.','Criar acento gráfico.'],answer:0,explanation:'A organização sintática também é expressiva.',tip:'O que ficou em evidência?'},{question:'Uma análise estilística deve considerar:',options:['O contexto.','Somente dicionário.','A quantidade de linhas.','A fonte.'],answer:0,explanation:'O efeito depende do uso contextual.',tip:'Contexto manda.'},{question:'Recursos sonoros podem contribuir para:',options:['Expressividade.','Regência apenas.','Crase apenas.','Concordância apenas.'],answer:0,explanation:'Aliteração e assonância são exemplos.',tip:'Som também produz efeito.'},{question:'Em prova, a pergunta central da estilística é:',options:['Que efeito essa escolha produz?','Quantas letras há?','Qual a cor do texto?','Quem imprimiu a prova?'],answer:0,explanation:'O foco é efeito de sentido.',tip:'Forma + efeito.'}]},
23:{title:'Figuras de linguagem',subtitle:'Português • Aula 23 • Edital • Figuras de linguagem',time:'55 min',content:`<div class="edital-badge">📋 EDITAL PMMG • FIGURAS DE LINGUAGEM</div><h3>Figuras mais cobradas</h3><p>Metáfora, metonímia, ironia, eufemismo, hipérbole, antítese, personificação, pleonasmo, aliteração e outras figuras alteram ou intensificam a expressão.</p><div class="lesson-example"><b>Exemplo:</b> “Ele é uma fera nos estudos.” Há metáfora: uma característica é transferida sem conectivo comparativo explícito.</div><div class="gold-rule">🎯 REGRA DE OURO: não decore só o nome; identifique o mecanismo e o efeito no trecho.</div><div class="video-lesson"><span>🔥 VIDEOAULA POPULAR • +380 MIL</span><h3>Figuras de linguagem — Português com Letícia</h3><p>Figuras sonoras e sintáticas com exemplos.</p><iframe src="https://www.youtube.com/embed/DZq92F2xg6c" title="Figuras de linguagem" allowfullscreen loading="lazy"></iframe></div>`,quiz:[
{question:'Metáfora é uma comparação:',options:['Implícita, por aproximação de sentidos.','Sempre com “como”.','Somente numérica.','Sem efeito de sentido.'],answer:0,explanation:'Transfere sentido por semelhança.',tip:'Comparação sem conectivo explícito.'},{question:'Hipérbole caracteriza:',options:['Exagero expressivo.','Suavização.','Oposição simples.','Imitação sonora.'],answer:0,explanation:'Intensifica por exagero.',tip:'“Esperei uma eternidade”.'},{question:'Eufemismo busca:',options:['Suavizar uma ideia.','Exagerar.','Imitar som.','Repetir conjunções.'],answer:0,explanation:'Ameniza expressão considerada dura.',tip:'Suavização.'},{question:'Antítese aproxima:',options:['Ideias opostas.','Sons idênticos apenas.','Verbos impessoais.','Pronomes relativos.'],answer:0,explanation:'Explora contraste.',tip:'Opostos.'},{question:'Personificação atribui:',options:['Características humanas a seres não humanos.','Números a palavras.','Acentos a verbos.','Preposições a nomes.'],answer:0,explanation:'Também chamada prosopopeia.',tip:'Humanização.'},{question:'Aliteração envolve repetição de:',options:['Sons consonantais.','Ideias opostas.','Artigos.','Tempos verbais.'],answer:0,explanation:'É figura sonora.',tip:'Som de consoantes.'}]}

};

// V6.4.3 — Prova Final de Português: 30 questões misturadas de toda a disciplina.
(function(){
  const pool=[];
  Object.keys(window.lessons).map(Number).filter(n=>n>=1&&n<=23).forEach(n=>{
    (window.lessons[n].quiz||[]).forEach(q=>pool.push({...q,lessonSource:n}));
  });
  const chosen=[]; const step=pool.length/30;
  for(let i=0;i<30;i++) chosen.push(pool[Math.floor(i*step)]);
  window.lessons[24]={title:"🏆 Prova Final — Língua Portuguesa",subtitle:"Português • Avaliação final • Aulas 01–23",time:"60 min",content:`<div class="edital-badge">🏆 PROVA FINAL • LÍNGUA PORTUGUESA</div><h3>Chegou a hora de consolidar Português</h3><p>Esta avaliação reúne <b>30 questões</b> de diferentes pontos estudados nas aulas 01 a 23. As alternativas são embaralhadas pelo sistema em cada tentativa.</p><div class="gold-rule">🎯 APROVAÇÃO: obtenha pelo menos <b>70%</b>. Se não atingir, use o Caderno de Erros e os Pontos Fracos para revisar antes de tentar novamente.</div><p>Você pode refazer esta prova sempre que quiser para revisão.</p>`,quiz:chosen};
})();


/* ==========================================================
   V6.4.4 — LITERATURA PMMG
   Edital DRH/CRS nº 10/2024: Campo Geral + Vidas Secas
   ========================================================== */
Object.assign(window.lessons,{
101:{subject:"Literatura",title:"Campo Geral — obra, contexto e narrador",subtitle:"Literatura • Aula 01 • Campo Geral",time:"45 min",content:`<div class="edital-badge">📋 EDITAL PMMG • CAMPO GERAL — JOÃO GUIMARÃES ROSA</div><h3>O que você precisa saber</h3><p><b>Campo Geral</b> é uma novela de João Guimarães Rosa centrada em Miguilim, menino que vive com a família no Mutúm, interior de Minas Gerais. A narrativa aproxima o leitor da percepção infantil do protagonista.</p><h3>Narrador e perspectiva</h3><p>Embora narrada em terceira pessoa, a história acompanha de perto a visão de Miguilim. Isso é essencial: acontecimentos familiares, natureza, medo, afeto e violência chegam ao leitor filtrados por sua sensibilidade.</p><div class="lesson-example"><b>Ponto de prova:</b> não confunda “narrador em terceira pessoa” com distanciamento. A focalização está fortemente ligada a Miguilim.</div><div class="gold-rule">🎯 REGRA DE OURO: em Campo Geral, pense em <b>infância + percepção de Miguilim + sertão mineiro + amadurecimento</b>.</div><div class="video-lesson"><span>🎥 VIDEOAULA • PMMG</span><h3>Campo Geral — Literatura para Soldado PMMG</h3><p>Aula direcionada ao concurso da Polícia Militar de Minas Gerais.</p><iframe src="https://www.youtube.com/embed/zCBH6pM_iHc" title="Campo Geral PMMG" allowfullscreen loading="lazy"></iframe></div>`,quiz:[
{question:"O protagonista de Campo Geral é:",options:["Miguilim.","Fabiano.","Paulo Honório.","Riobaldo."],answer:0,explanation:"Miguilim é o centro da narrativa.",tip:"Campo Geral = infância de Miguilim."},
{question:"O espaço central da obra é:",options:["Mutúm, no sertão mineiro.","Rio de Janeiro.","São Paulo.","Recife urbano."],answer:0,explanation:"A família vive no Mutúm, em Minas Gerais.",tip:"Associe Mutúm a Campo Geral."},
{question:"A perspectiva narrativa aproxima o leitor principalmente de:",options:["Miguilim.","Um juiz.","Um soldado.","Um narrador-personagem adulto."],answer:0,explanation:"A focalização acompanha a percepção de Miguilim.",tip:"Veja o mundo pelos olhos do menino."},
{question:"Campo Geral é obra de:",options:["João Guimarães Rosa.","Graciliano Ramos.","Machado de Assis.","José de Alencar."],answer:0,explanation:"João Guimarães Rosa é o autor.",tip:"Rosa → Campo Geral."},
{question:"Um eixo importante da obra é:",options:["Infância e amadurecimento.","Viagem espacial.","Vida na corte portuguesa.","Investigação policial."],answer:0,explanation:"A experiência infantil e o amadurecimento estruturam a obra.",tip:"Miguilim cresce ao longo das experiências."},
{question:"A ambientação de Campo Geral se relaciona fortemente:",options:["À natureza e ao sertão de Minas Gerais.","Ao litoral europeu.","À metrópole industrial.","A uma ilha fictícia."],answer:0,explanation:"O sertão mineiro e a natureza são fundamentais.",tip:"Espaço também produz sentido."}
]},
102:{subject:"Literatura",title:"Campo Geral — personagens, conflitos e amadurecimento",subtitle:"Literatura • Aula 02 • Campo Geral",time:"50 min",content:`<div class="edital-badge">📋 EDITAL PMMG • CAMPO GERAL — PERSONAGENS</div><h3>Miguilim e Dito</h3><p>Miguilim mantém forte vínculo afetivo com o irmão Dito. A relação entre os dois é central para a formação emocional do protagonista.</p><h3>Família e tensão</h3><p>A vida familiar é marcada por afeto, incompreensão, dureza e conflitos. O pai de Miguilim é uma figura severa, enquanto a criança tenta compreender as tensões do mundo adulto.</p><h3>Visão e descoberta</h3><p>Um dos momentos simbólicos do final envolve a descoberta da miopia de Miguilim. Ao usar óculos, ele passa a enxergar o mundo com nitidez — fato concreto que também dialoga com seu processo de transformação.</p><div class="gold-rule">🎯 REGRA DE OURO: Dito, família, perda e visão são pontos-chave para entender o amadurecimento de Miguilim.</div><div class="video-lesson"><span>🔥 VIDEOAULA POPULAR • RESUMO + ANÁLISE</span><h3>Campo Geral — resumo e análise</h3><p>Revisão da obra, personagens e principais temas.</p><iframe src="https://www.youtube.com/embed/Rgit7L7WU3E" title="Campo Geral resumo e análise" allowfullscreen loading="lazy"></iframe></div>`,quiz:[
{question:"Dito é:",options:["Irmão de Miguilim.","Pai de Miguilim.","Professor de Miguilim.","Narrador da obra."],answer:0,explanation:"Dito é irmão de Miguilim e figura afetiva central.",tip:"Miguilim e Dito têm forte vínculo."},
{question:"A família de Miguilim é apresentada como:",options:["Marcada por afetos e conflitos.","Sem qualquer tensão.","Uma família urbana rica.","Um grupo de militares."],answer:0,explanation:"A narrativa mostra relações familiares complexas.",tip:"Infância não é idealizada."},
{question:"A descoberta da miopia de Miguilim está ligada:",options:["À possibilidade de enxergar com nitidez.","À perda da fala.","À mudança para o exterior.","Ao abandono da família."],answer:0,explanation:"Os óculos revelam uma nova nitidez visual.",tip:"Visão literal e transformação dialogam."},
{question:"O pai de Miguilim aparece frequentemente como figura:",options:["Severa e conflituosa.","Cômica e ausente de conflitos.","Fantástica.","Narradora."],answer:0,explanation:"A dureza paterna participa das tensões familiares.",tip:"Observe a experiência infantil diante dos adultos."},
{question:"A relação com Dito contribui para:",options:["A formação emocional de Miguilim.","Apagar o protagonismo.","Transformar a obra em comédia.","Eliminar os conflitos."],answer:0,explanation:"Dito é decisivo no universo afetivo do protagonista.",tip:"Personagens moldam o amadurecimento."},
{question:"O amadurecimento de Miguilim ocorre:",options:["Por meio das experiências, perdas e descobertas.","Sem acontecimentos relevantes.","Apenas por estudo escolar.","Por uma viagem à Europa."],answer:0,explanation:"As experiências vividas transformam sua percepção.",tip:"Formação = experiência."}
]},
103:{subject:"Literatura",title:"Campo Geral — linguagem, temas e questões PMMG",subtitle:"Literatura • Aula 03 • Campo Geral",time:"50 min",content:`<div class="edital-badge">📋 EDITAL PMMG • CAMPO GERAL — ANÁLISE</div><h3>Linguagem rosiana</h3><p>Guimarães Rosa explora oralidade, regionalismos, invenções vocabulares e grande força poética. A linguagem não é mero enfeite: ajuda a construir a experiência do sertão e a percepção das personagens.</p><h3>Temas recorrentes</h3><p>Infância, família, violência, natureza, morte, afeto, descoberta e passagem para uma nova etapa da vida aparecem de forma articulada.</p><div class="lesson-example"><b>Como a banca pode cobrar:</b> relação entre narrador e perspectiva de Miguilim; função simbólica da visão; personagens; espaço; linguagem e amadurecimento.</div><div class="gold-rule">🎯 REGRA DE OURO: em Literatura, responda pela obra — não pelo que “parece mais bonito”.</div>`,quiz:[
{question:"A linguagem de Guimarães Rosa em Campo Geral pode ser associada a:",options:["Regionalismo, oralidade e criação expressiva.","Linguagem exclusivamente burocrática.","Vocabulário matemático.","Ausência de marcas regionais."],answer:0,explanation:"A elaboração linguística é característica marcante de Rosa.",tip:"Rosa recria a língua literária."},
{question:"A natureza na obra:",options:["Integra a experiência das personagens.","É irrelevante.","Aparece apenas no título.","É sempre cenário urbano."],answer:0,explanation:"O ambiente natural participa da construção de sentidos.",tip:"Sertão e personagem dialogam."},
{question:"A perspectiva infantil contribui para:",options:["Uma percepção sensível e particular do mundo adulto.","Eliminar conflitos.","Transformar o texto em documento jurídico.","Criar narrador em primeira pessoa obrigatoriamente."],answer:0,explanation:"A focalização aproxima o leitor da experiência de Miguilim.",tip:"Terceira pessoa pode acompanhar uma consciência."},
{question:"Entre os temas de Campo Geral está:",options:["Perda e amadurecimento.","Colonização espacial.","Tecnologia digital.","Vida parlamentar."],answer:0,explanation:"Perdas e descobertas participam da formação de Miguilim.",tip:"Pense em romance/novela de formação."},
{question:"Para responder questão sobre a obra, o mais seguro é:",options:["Relacionar alternativa a fatos e elementos efetivos da narrativa.","Usar apenas opinião pessoal.","Escolher a alternativa mais longa.","Ignorar personagens."],answer:0,explanation:"A prova cobra conhecimento e interpretação da obra.",tip:"Evidência da narrativa primeiro."},
{question:"A visão de Miguilim no final pode ser lida também como:",options:["Imagem ligada à descoberta de um mundo antes pouco nítido.","Prova de que ele era cego.","Rejeição da natureza.","Mudança do narrador para primeira pessoa."],answer:0,explanation:"A nitidez visual reforça o movimento de descoberta.",tip:"Símbolos dialogam com fatos concretos."}
]},
104:{subject:"Literatura",title:"Vidas Secas — estrutura, narrador e retirantes",subtitle:"Literatura • Aula 04 • Vidas Secas",time:"50 min",content:`<div class="edital-badge">📋 EDITAL PMMG • VIDAS SECAS — GRACILIANO RAMOS</div><h3>A família de retirantes</h3><p><b>Vidas Secas</b> acompanha Fabiano, Sinhá Vitória, os dois meninos e a cachorra Baleia em sua luta pela sobrevivência no sertão nordestino.</p><h3>Narrador e estrutura</h3><p>O narrador é em terceira pessoa e penetra a interioridade das personagens. Os capítulos têm relativa autonomia, formando uma estrutura que reforça o movimento cíclico da retirada e da sobrevivência.</p><h3>Seca e desigualdade</h3><p>A seca é fundamental, mas a obra não reduz o sofrimento à natureza: exploração econômica, abuso de poder, pobreza e dificuldade de comunicação também pesam sobre as personagens.</p><div class="gold-rule">🎯 REGRA DE OURO: Vidas Secas = <b>seca + pobreza + opressão + linguagem econômica + ciclo de retirada</b>.</div><div class="video-lesson"><span>🎥 VIDEOAULA • PMMG</span><h3>Vidas Secas — Literatura para Soldado PMMG</h3><p>Aula específica para o concurso da PMMG.</p><iframe src="https://www.youtube.com/embed/4KclON0xfkU" title="Vidas Secas PMMG" allowfullscreen loading="lazy"></iframe></div>`,quiz:[
{question:"A família central de Vidas Secas inclui:",options:["Fabiano, Sinhá Vitória, dois meninos e Baleia.","Miguilim e Dito.","Bentinho e Capitu.","Macabéa e Olímpico apenas."],answer:0,explanation:"Essas são as figuras centrais da família retirante.",tip:"Não misture as duas obras do edital."},
{question:"O espaço predominante é:",options:["O sertão nordestino.","O sertão mineiro do Mutúm.","A corte do Rio de Janeiro.","Uma capital europeia."],answer:0,explanation:"A obra acompanha retirantes no sertão nordestino.",tip:"Vidas Secas → Nordeste."},
{question:"O narrador é:",options:["Em terceira pessoa, com acesso à interioridade das personagens.","Sempre Fabiano em primeira pessoa.","Baleia em primeira pessoa.","Um narrador documental sem acesso interior."],answer:0,explanation:"A terceira pessoa aproxima o leitor dos pensamentos das personagens.",tip:"Onisciência e focalização variam por capítulo."},
{question:"A seca na obra:",options:["Relaciona-se também a problemas sociais e econômicos.","É a única adversidade existente.","Não interfere na narrativa.","É apenas metáfora sem efeito concreto."],answer:0,explanation:"A obra articula natureza e estruturas de opressão.",tip:"Não reduza tudo ao clima."},
{question:"A estrutura da obra é frequentemente percebida como:",options:["Cíclica, com capítulos de relativa autonomia.","Uma sequência policial linear.","Um diário em primeira pessoa.","Uma peça teatral."],answer:0,explanation:"O ciclo da retirada é estruturalmente importante.",tip:"Começo e fim dialogam."},
{question:"Vidas Secas é obra de:",options:["Graciliano Ramos.","Guimarães Rosa.","Carlos Drummond.","Clarice Lispector."],answer:0,explanation:"Graciliano Ramos escreveu Vidas Secas.",tip:"Graciliano → Vidas Secas."}
]},
105:{subject:"Literatura",title:"Vidas Secas — personagens, linguagem e opressão",subtitle:"Literatura • Aula 05 • Vidas Secas",time:"55 min",content:`<div class="edital-badge">📋 EDITAL PMMG • VIDAS SECAS — PERSONAGENS</div><h3>Fabiano e a dificuldade de expressão</h3><p>Fabiano vive entre a submissão e a revolta. Sua limitação verbal aparece ligada à exclusão social e à dificuldade de defender-se diante das instituições e de quem exerce poder.</p><h3>Sinhá Vitória</h3><p>É prática, resistente e alimenta o desejo de melhorar a vida da família. O sonho de possuir uma cama de couro aparece como símbolo de uma existência mais digna e estável.</p><h3>Baleia</h3><p>A cachorra recebe tratamento humanizado e possui um dos capítulos mais conhecidos da obra. A interioridade atribuída a Baleia contrasta com processos de desumanização vividos pelas pessoas.</p><div class="gold-rule">🎯 REGRA DE OURO: observe o contraste entre <b>humanização de Baleia</b> e <b>desumanização social dos retirantes</b>.</div><div class="video-lesson"><span>🎥 REVISÃO RÁPIDA • PMMG</span><h3>Vidas Secas em 5 minutos — PMMG</h3><p>Resumo rápido para reforçar personagens e temas.</p><iframe src="https://www.youtube.com/embed/jeoWc-rAm_4" title="Vidas Secas resumo PMMG" allowfullscreen loading="lazy"></iframe></div>`,quiz:[
{question:"O sonho recorrente de Sinhá Vitória envolve:",options:["Uma cama de couro.","Um automóvel.","Uma viagem à Europa.","Uma fazenda de café."],answer:0,explanation:"A cama simboliza conforto e estabilidade desejados.",tip:"Pequeno objeto, grande significado."},
{question:"Baleia é:",options:["A cachorra da família.","Uma professora.","A mãe de Fabiano.","Uma cidade."],answer:0,explanation:"Baleia é a cachorra da família e personagem marcante.",tip:"Seu capítulo é central."},
{question:"A dificuldade de linguagem de Fabiano se relaciona:",options:["À exclusão e à dificuldade de se defender socialmente.","À formação universitária.","À profissão de escritor.","A um jogo cômico sem consequência."],answer:0,explanation:"A limitação verbal tem dimensão social.",tip:"Linguagem também é poder."},
{question:"O tratamento dado a Baleia pode ser entendido como:",options:["Humanização do animal.","Eliminação de qualquer interioridade.","Descrição científica.","Ausência de afeto."],answer:0,explanation:"O narrador atribui interioridade e sensibilidade a Baleia.",tip:"Compare com a desumanização dos humanos."},
{question:"Sinhá Vitória é caracterizada também por:",options:["Resistência e desejo de melhorar a vida.","Desinteresse completo pelo futuro.","Ser a antagonista principal.","Viver fora do sertão."],answer:0,explanation:"Ela projeta uma vida mais digna para a família.",tip:"Sonho e resistência."},
{question:"A opressão em Vidas Secas:",options:["Vai além da seca e inclui relações sociais de poder.","É inexistente.","É somente familiar.","É exclusivamente religiosa."],answer:0,explanation:"Exploração e abuso institucional aparecem na obra.",tip:"Natureza + sociedade."}
]},
106:{subject:"Literatura",title:"Vidas Secas — temas, símbolos e comparação das obras",subtitle:"Literatura • Aula 06 • Revisão comparativa",time:"55 min",content:`<div class="edital-badge">📋 EDITAL PMMG • REVISÃO DAS DUAS OBRAS</div><h3>Vidas Secas</h3><p>Economia de linguagem, sobrevivência, seca, desigualdade, opressão, incomunicabilidade e ciclo de retirada são eixos fortes.</p><h3>Campo Geral</h3><p>Infância, sensibilidade, família, natureza, violência, perda, linguagem rosiana e amadurecimento de Miguilim são eixos fortes.</p><h3>Não misture</h3><p><b>Miguilim / Mutúm / Dito / Guimarães Rosa</b> pertencem a Campo Geral. <b>Fabiano / Sinhá Vitória / Baleia / sertão nordestino / Graciliano Ramos</b> pertencem a Vidas Secas.</p><div class="lesson-example"><b>Estratégia de prova:</b> antes de avaliar a afirmação, identifique a qual obra, personagem e espaço ela pertence.</div><div class="gold-rule">🎯 REGRA DE OURO: faça uma tabela mental das duas obras para evitar trocas de personagens e características.</div>`,quiz:[
{question:"Miguilim pertence a:",options:["Campo Geral.","Vidas Secas.","Memórias Póstumas.","O Cortiço."],answer:0,explanation:"Miguilim protagoniza Campo Geral.",tip:"Miguilim → Rosa."},
{question:"Baleia pertence a:",options:["Vidas Secas.","Campo Geral.","Grande Sertão: Veredas.","Dom Casmurro."],answer:0,explanation:"Baleia é a cachorra da família de Fabiano.",tip:"Baleia → Graciliano."},
{question:"Mutúm está associado a:",options:["Campo Geral.","Vidas Secas.","Capitães da Areia.","Iracema."],answer:0,explanation:"É o espaço central da família de Miguilim.",tip:"Mutúm → Minas."},
{question:"O ciclo de retirada é especialmente importante em:",options:["Vidas Secas.","Campo Geral apenas.","Nenhuma das duas.","Uma peça teatral."],answer:0,explanation:"A estrutura cíclica reforça a condição dos retirantes.",tip:"Fuga da seca e recomeço."},
{question:"A descoberta da miopia é marcante em:",options:["Campo Geral.","Vidas Secas.","Ambas exatamente do mesmo modo.","Nenhuma."],answer:0,explanation:"Miguilim descobre a miopia.",tip:"Óculos → Miguilim."},
{question:"A cama de couro é desejo de:",options:["Sinhá Vitória.","Nhanina.","Miguilim.","Dito."],answer:0,explanation:"É sonho de Sinhá Vitória em Vidas Secas.",tip:"Cama → estabilidade."}
]},
107:{subject:"Literatura",title:"🏆 Prova Final — Literatura",subtitle:"Literatura • Avaliação final • Campo Geral + Vidas Secas",time:"45 min",content:`<div class="edital-badge">🏆 PROVA FINAL • LITERATURA PMMG</div><h3>Fechamento da disciplina</h3><p>Esta prova reúne 20 questões e mistura as duas obras exigidas no edital: <b>Campo Geral</b>, de João Guimarães Rosa, e <b>Vidas Secas</b>, de Graciliano Ramos.</p><p>As alternativas são embaralhadas em cada tentativa.</p><div class="gold-rule">🎯 APROVAÇÃO: mínimo de <b>70%</b>. Se não atingir, revise as aulas e o Caderno de Erros.</div>`,quiz:[
{question:"Assinale a associação correta:",options:["Miguilim — Campo Geral.","Miguilim — Vidas Secas.","Baleia — Campo Geral.","Fabiano — Campo Geral."],answer:0,explanation:"Miguilim protagoniza Campo Geral.",tip:"Separe as personagens por obra."},
{question:"Vidas Secas foi escrito por:",options:["Graciliano Ramos.","Guimarães Rosa.","Machado de Assis.","Drummond."],answer:0,explanation:"Graciliano Ramos é o autor.",tip:"Graciliano → Vidas Secas."},
{question:"Campo Geral acompanha principalmente:",options:["A experiência e o amadurecimento de Miguilim.","A carreira militar de Fabiano.","Uma família urbana no Rio.","Uma investigação criminal."],answer:0,explanation:"Miguilim e sua formação são centrais.",tip:"Infância e percepção."},
{question:"Em Vidas Secas, a seca:",options:["Articula-se a problemas sociais e econômicos.","É a única dificuldade existente.","Não interfere na vida da família.","É apenas um sonho."],answer:0,explanation:"A obra também aborda exploração, pobreza e opressão.",tip:"Natureza + sociedade."},
{question:"Dito é personagem de:",options:["Campo Geral.","Vidas Secas.","Nenhuma das obras.","Vidas Secas e narrador."],answer:0,explanation:"Dito é irmão de Miguilim.",tip:"Dito → Miguilim."},
{question:"Sinhá Vitória deseja especialmente:",options:["Uma cama de couro.","Óculos para Miguilim.","Mudar para Mutúm.","Ser escritora."],answer:0,explanation:"A cama simboliza estabilidade e conforto.",tip:"Objeto simbólico de Vidas Secas."},
{question:"A descoberta da miopia ocorre com:",options:["Miguilim.","Fabiano.","Sinhá Vitória.","Baleia."],answer:0,explanation:"Miguilim passa a enxergar nitidamente com óculos.",tip:"Visão → Campo Geral."},
{question:"A humanização de Baleia contrasta com:",options:["A desumanização social vivida pelos retirantes.","A riqueza da família.","A vida urbana confortável.","A ausência de sofrimento."],answer:0,explanation:"Esse contraste é importante na obra.",tip:"Animal humanizado x humanos oprimidos."},
{question:"A linguagem de Guimarães Rosa em Campo Geral destaca:",options:["Oralidade, regionalismo e invenção expressiva.","Somente linguagem jurídica.","Ausência de marcas regionais.","Vocabulário técnico científico."],answer:0,explanation:"A elaboração linguística é característica rosiana.",tip:"Rosa recria a linguagem."},
{question:"A estrutura de Vidas Secas é frequentemente descrita como:",options:["Cíclica, com capítulos relativamente autônomos.","Teatral em cinco atos.","Diário em primeira pessoa.","Poema épico."],answer:0,explanation:"O movimento de retirada e recomeço reforça o ciclo.",tip:"Início e fim se correspondem."},
{question:"O Mutúm pertence ao universo de:",options:["Campo Geral.","Vidas Secas.","Ambas as obras.","Nenhuma das obras."],answer:0,explanation:"É o espaço central de Campo Geral.",tip:"Mutúm → Minas Gerais."},
{question:"Fabiano apresenta dificuldade de expressão que se relaciona:",options:["À exclusão e às relações de poder.","À formação acadêmica.","Ao trabalho de jornalista.","A um recurso sem função social."],answer:0,explanation:"A limitação verbal participa da condição social da personagem.",tip:"Linguagem é poder."},
{question:"Qual par está correto?",options:["Guimarães Rosa — Campo Geral.","Guimarães Rosa — Vidas Secas.","Graciliano Ramos — Campo Geral.","Miguilim — Vidas Secas."],answer:0,explanation:"Guimarães Rosa escreveu Campo Geral.",tip:"Autor e obra."},
{question:"Um tema comum às duas obras é:",options:["A dureza da vida no sertão e relações humanas complexas.","Tecnologia digital.","Vida aristocrática europeia.","Exploração espacial."],answer:0,explanation:"As duas obras trabalham experiências humanas em ambientes sertanejos, embora de modos diferentes.",tip:"Compare sem igualar."},
{question:"Para a prova da PMMG, Literatura no edital trabalhado cobra:",options:["Campo Geral e Vidas Secas.","Somente poesia de Camões.","Dom Casmurro e O Cortiço.","Apenas teoria literária abstrata."],answer:0,explanation:"São as duas obras expressamente indicadas.",tip:"Duas obras obrigatórias."}
,{question:"Em Campo Geral, a focalização narrativa aproxima o leitor de:",options:["Miguilim e sua percepção infantil.","Fabiano e sua vida de retirante.","Baleia como narradora.","Um juiz urbano."],answer:0,explanation:"A narrativa acompanha de perto a percepção de Miguilim.",tip:"Terceira pessoa pode focalizar uma personagem."},
{question:"Em Vidas Secas, o Soldado Amarelo evidencia:",options:["Abuso de autoridade e impotência social de Fabiano.","Prosperidade da família.","A infância de Miguilim.","A descoberta da miopia."],answer:0,explanation:"O episódio expõe relações de poder e submissão.",tip:"Fabiano enfrenta também opressão social."},
{question:"Qual comparação está correta?",options:["Campo Geral enfatiza Miguilim; Vidas Secas acompanha retirantes.","As duas obras são narradas por Miguilim.","Baleia e Dito pertencem a Campo Geral.","As duas se passam no Mutúm."],answer:0,explanation:"As obras têm universos próprios e não devem ser confundidas.",tip:"Separe personagens, autores e espaços."},
{question:"A economia de linguagem é especialmente associada a:",options:["Vidas Secas, de Graciliano Ramos.","Campo Geral como texto jurídico.","Nenhuma das obras.","Somente aos diálogos de Dito."],answer:0,explanation:"A escrita enxuta é marca importante de Graciliano Ramos.",tip:"Graciliano → linguagem concisa."},
{question:"Uma revisão eficiente das duas obras deve relacionar:",options:["Autor, personagens, espaço, narrador, temas e episódios centrais.","Somente datas de publicação.","Apenas nomes dos autores.","Personagens misturados das duas obras."],answer:0,explanation:"A prova pode cruzar diferentes elementos das obras.",tip:"Faça uma ficha mental para cada obra."}
]}
});
