/* Missão PMMG V6.4.5 — Literatura separada por matéria.
   Numeração própria: Aula 01 a Aula 06 + Prova Final 07.
*/
window.literaturaLessons={
1:{title:"Campo Geral — obra, contexto e narrador",subtitle:"Literatura • Aula 01 • Campo Geral",time:"45 min",content:`<div class="edital-badge">📋 EDITAL PMMG • CAMPO GERAL — JOÃO GUIMARÃES ROSA</div><h3>O que você precisa saber</h3><p><b>Campo Geral</b> é uma novela de João Guimarães Rosa centrada em Miguilim, menino que vive com a família no Mutúm, interior de Minas Gerais. A narrativa aproxima o leitor da percepção infantil do protagonista.</p><h3>Narrador e perspectiva</h3><p>Embora narrada em terceira pessoa, a história acompanha de perto a visão de Miguilim. Isso é essencial: acontecimentos familiares, natureza, medo, afeto e violência chegam ao leitor filtrados por sua sensibilidade.</p><div class="lesson-example"><b>Ponto de prova:</b> não confunda “narrador em terceira pessoa” com distanciamento. A focalização está fortemente ligada a Miguilim.</div><div class="gold-rule">🎯 REGRA DE OURO: em Campo Geral, pense em <b>infância + percepção de Miguilim + sertão mineiro + amadurecimento</b>.</div><div class="video-lesson"><span>🎥 VIDEOAULA • PMMG</span><h3>Campo Geral — Literatura para Soldado PMMG</h3><p>Aula direcionada ao concurso da Polícia Militar de Minas Gerais.</p><iframe src="https://www.youtube.com/embed/zCBH6pM_iHc" title="Campo Geral PMMG" allowfullscreen loading="lazy"></iframe></div>`,quiz:[
{question:"O protagonista de Campo Geral é:",options:["Miguilim.","Fabiano.","Paulo Honório.","Riobaldo."],answer:0,explanation:"Miguilim é o centro da narrativa.",tip:"Campo Geral = infância de Miguilim."},
{question:"O espaço central da obra é:",options:["Mutúm, no sertão mineiro.","Rio de Janeiro.","São Paulo.","Recife urbano."],answer:0,explanation:"A família vive no Mutúm, em Minas Gerais.",tip:"Associe Mutúm a Campo Geral."},
{question:"A perspectiva narrativa aproxima o leitor principalmente de:",options:["Miguilim.","Um juiz.","Um soldado.","Um narrador-personagem adulto."],answer:0,explanation:"A focalização acompanha a percepção de Miguilim.",tip:"Veja o mundo pelos olhos do menino."},
{question:"Campo Geral é obra de:",options:["João Guimarães Rosa.","Graciliano Ramos.","Machado de Assis.","José de Alencar."],answer:0,explanation:"João Guimarães Rosa é o autor.",tip:"Rosa → Campo Geral."},
{question:"Um eixo importante da obra é:",options:["Infância e amadurecimento.","Viagem espacial.","Vida na corte portuguesa.","Investigação policial."],answer:0,explanation:"A experiência infantil e o amadurecimento estruturam a obra.",tip:"Miguilim cresce ao longo das experiências."},
{question:"A ambientação de Campo Geral se relaciona fortemente:",options:["À natureza e ao sertão de Minas Gerais.","Ao litoral europeu.","À metrópole industrial.","A uma ilha fictícia."],answer:0,explanation:"O sertão mineiro e a natureza são fundamentais.",tip:"Espaço também produz sentido."}
]},
2:{title:"Campo Geral — personagens, conflitos e amadurecimento",subtitle:"Literatura • Aula 02 • Campo Geral",time:"50 min",content:`<div class="edital-badge">📋 EDITAL PMMG • CAMPO GERAL — PERSONAGENS</div><h3>Miguilim e Dito</h3><p>Miguilim mantém forte vínculo afetivo com o irmão Dito. A relação entre os dois é central para a formação emocional do protagonista.</p><h3>Família e tensão</h3><p>A vida familiar é marcada por afeto, incompreensão, dureza e conflitos. O pai de Miguilim é uma figura severa, enquanto a criança tenta compreender as tensões do mundo adulto.</p><h3>Visão e descoberta</h3><p>Um dos momentos simbólicos do final envolve a descoberta da miopia de Miguilim. Ao usar óculos, ele passa a enxergar o mundo com nitidez — fato concreto que também dialoga com seu processo de transformação.</p><div class="gold-rule">🎯 REGRA DE OURO: Dito, família, perda e visão são pontos-chave para entender o amadurecimento de Miguilim.</div><div class="video-lesson"><span>🔥 VIDEOAULA POPULAR • RESUMO + ANÁLISE</span><h3>Campo Geral — resumo e análise</h3><p>Revisão da obra, personagens e principais temas.</p><iframe src="https://www.youtube.com/embed/Rgit7L7WU3E" title="Campo Geral resumo e análise" allowfullscreen loading="lazy"></iframe></div>`,quiz:[
{question:"Dito é:",options:["Irmão de Miguilim.","Pai de Miguilim.","Professor de Miguilim.","Narrador da obra."],answer:0,explanation:"Dito é irmão de Miguilim e figura afetiva central.",tip:"Miguilim e Dito têm forte vínculo."},
{question:"A família de Miguilim é apresentada como:",options:["Marcada por afetos e conflitos.","Sem qualquer tensão.","Uma família urbana rica.","Um grupo de militares."],answer:0,explanation:"A narrativa mostra relações familiares complexas.",tip:"Infância não é idealizada."},
{question:"A descoberta da miopia de Miguilim está ligada:",options:["À possibilidade de enxergar com nitidez.","À perda da fala.","À mudança para o exterior.","Ao abandono da família."],answer:0,explanation:"Os óculos revelam uma nova nitidez visual.",tip:"Visão literal e transformação dialogam."},
{question:"O pai de Miguilim aparece frequentemente como figura:",options:["Severa e conflituosa.","Cômica e ausente de conflitos.","Fantástica.","Narradora."],answer:0,explanation:"A dureza paterna participa das tensões familiares.",tip:"Observe a experiência infantil diante dos adultos."},
{question:"A relação com Dito contribui para:",options:["A formação emocional de Miguilim.","Apagar o protagonismo.","Transformar a obra em comédia.","Eliminar os conflitos."],answer:0,explanation:"Dito é decisivo no universo afetivo do protagonista.",tip:"Personagens moldam o amadurecimento."},
{question:"O amadurecimento de Miguilim ocorre:",options:["Por meio das experiências, perdas e descobertas.","Sem acontecimentos relevantes.","Apenas por estudo escolar.","Por uma viagem à Europa."],answer:0,explanation:"As experiências vividas transformam sua percepção.",tip:"Formação = experiência."}
]},
3:{title:"Campo Geral — linguagem, temas e questões PMMG",subtitle:"Literatura • Aula 03 • Campo Geral",time:"50 min",content:`<div class="edital-badge">📋 EDITAL PMMG • CAMPO GERAL — ANÁLISE</div><h3>Linguagem rosiana</h3><p>Guimarães Rosa explora oralidade, regionalismos, invenções vocabulares e grande força poética. A linguagem não é mero enfeite: ajuda a construir a experiência do sertão e a percepção das personagens.</p><h3>Temas recorrentes</h3><p>Infância, família, violência, natureza, morte, afeto, descoberta e passagem para uma nova etapa da vida aparecem de forma articulada.</p><div class="lesson-example"><b>Como a banca pode cobrar:</b> relação entre narrador e perspectiva de Miguilim; função simbólica da visão; personagens; espaço; linguagem e amadurecimento.</div><div class="gold-rule">🎯 REGRA DE OURO: em Literatura, responda pela obra — não pelo que “parece mais bonito”.</div>`,quiz:[
{question:"A linguagem de Guimarães Rosa em Campo Geral pode ser associada a:",options:["Regionalismo, oralidade e criação expressiva.","Linguagem exclusivamente burocrática.","Vocabulário matemático.","Ausência de marcas regionais."],answer:0,explanation:"A elaboração linguística é característica marcante de Rosa.",tip:"Rosa recria a língua literária."},
{question:"A natureza na obra:",options:["Integra a experiência das personagens.","É irrelevante.","Aparece apenas no título.","É sempre cenário urbano."],answer:0,explanation:"O ambiente natural participa da construção de sentidos.",tip:"Sertão e personagem dialogam."},
{question:"A perspectiva infantil contribui para:",options:["Uma percepção sensível e particular do mundo adulto.","Eliminar conflitos.","Transformar o texto em documento jurídico.","Criar narrador em primeira pessoa obrigatoriamente."],answer:0,explanation:"A focalização aproxima o leitor da experiência de Miguilim.",tip:"Terceira pessoa pode acompanhar uma consciência."},
{question:"Entre os temas de Campo Geral está:",options:["Perda e amadurecimento.","Colonização espacial.","Tecnologia digital.","Vida parlamentar."],answer:0,explanation:"Perdas e descobertas participam da formação de Miguilim.",tip:"Pense em romance/novela de formação."},
{question:"Para responder questão sobre a obra, o mais seguro é:",options:["Relacionar alternativa a fatos e elementos efetivos da narrativa.","Usar apenas opinião pessoal.","Escolher a alternativa mais longa.","Ignorar personagens."],answer:0,explanation:"A prova cobra conhecimento e interpretação da obra.",tip:"Evidência da narrativa primeiro."},
{question:"A visão de Miguilim no final pode ser lida também como:",options:["Imagem ligada à descoberta de um mundo antes pouco nítido.","Prova de que ele era cego.","Rejeição da natureza.","Mudança do narrador para primeira pessoa."],answer:0,explanation:"A nitidez visual reforça o movimento de descoberta.",tip:"Símbolos dialogam com fatos concretos."}
]},
4:{title:"Vidas Secas — estrutura, narrador e retirantes",subtitle:"Literatura • Aula 04 • Vidas Secas",time:"50 min",content:`<div class="edital-badge">📋 EDITAL PMMG • VIDAS SECAS — GRACILIANO RAMOS</div><h3>A família de retirantes</h3><p><b>Vidas Secas</b> acompanha Fabiano, Sinhá Vitória, os dois meninos e a cachorra Baleia em sua luta pela sobrevivência no sertão nordestino.</p><h3>Narrador e estrutura</h3><p>O narrador é em terceira pessoa e penetra a interioridade das personagens. Os capítulos têm relativa autonomia, formando uma estrutura que reforça o movimento cíclico da retirada e da sobrevivência.</p><h3>Seca e desigualdade</h3><p>A seca é fundamental, mas a obra não reduz o sofrimento à natureza: exploração econômica, abuso de poder, pobreza e dificuldade de comunicação também pesam sobre as personagens.</p><div class="gold-rule">🎯 REGRA DE OURO: Vidas Secas = <b>seca + pobreza + opressão + linguagem econômica + ciclo de retirada</b>.</div><div class="video-lesson"><span>🎥 VIDEOAULA • PMMG</span><h3>Vidas Secas — Literatura para Soldado PMMG</h3><p>Aula específica para o concurso da PMMG.</p><iframe src="https://www.youtube.com/embed/4KclON0xfkU" title="Vidas Secas PMMG" allowfullscreen loading="lazy"></iframe></div>`,quiz:[
{question:"A família central de Vidas Secas inclui:",options:["Fabiano, Sinhá Vitória, dois meninos e Baleia.","Miguilim e Dito.","Bentinho e Capitu.","Macabéa e Olímpico apenas."],answer:0,explanation:"Essas são as figuras centrais da família retirante.",tip:"Não misture as duas obras do edital."},
{question:"O espaço predominante é:",options:["O sertão nordestino.","O sertão mineiro do Mutúm.","A corte do Rio de Janeiro.","Uma capital europeia."],answer:0,explanation:"A obra acompanha retirantes no sertão nordestino.",tip:"Vidas Secas → Nordeste."},
{question:"O narrador é:",options:["Em terceira pessoa, com acesso à interioridade das personagens.","Sempre Fabiano em primeira pessoa.","Baleia em primeira pessoa.","Um narrador documental sem acesso interior."],answer:0,explanation:"A terceira pessoa aproxima o leitor dos pensamentos das personagens.",tip:"Onisciência e focalização variam por capítulo."},
{question:"A seca na obra:",options:["Relaciona-se também a problemas sociais e econômicos.","É a única adversidade existente.","Não interfere na narrativa.","É apenas metáfora sem efeito concreto."],answer:0,explanation:"A obra articula natureza e estruturas de opressão.",tip:"Não reduza tudo ao clima."},
{question:"A estrutura da obra é frequentemente percebida como:",options:["Cíclica, com capítulos de relativa autonomia.","Uma sequência policial linear.","Um diário em primeira pessoa.","Uma peça teatral."],answer:0,explanation:"O ciclo da retirada é estruturalmente importante.",tip:"Começo e fim dialogam."},
{question:"Vidas Secas é obra de:",options:["Graciliano Ramos.","Guimarães Rosa.","Carlos Drummond.","Clarice Lispector."],answer:0,explanation:"Graciliano Ramos escreveu Vidas Secas.",tip:"Graciliano → Vidas Secas."}
]},
5:{title:"Vidas Secas — personagens, linguagem e opressão",subtitle:"Literatura • Aula 05 • Vidas Secas",time:"55 min",content:`<div class="edital-badge">📋 EDITAL PMMG • VIDAS SECAS — PERSONAGENS</div><h3>Fabiano e a dificuldade de expressão</h3><p>Fabiano vive entre a submissão e a revolta. Sua limitação verbal aparece ligada à exclusão social e à dificuldade de defender-se diante das instituições e de quem exerce poder.</p><h3>Sinhá Vitória</h3><p>É prática, resistente e alimenta o desejo de melhorar a vida da família. O sonho de possuir uma cama de couro aparece como símbolo de uma existência mais digna e estável.</p><h3>Baleia</h3><p>A cachorra recebe tratamento humanizado e possui um dos capítulos mais conhecidos da obra. A interioridade atribuída a Baleia contrasta com processos de desumanização vividos pelas pessoas.</p><div class="gold-rule">🎯 REGRA DE OURO: observe o contraste entre <b>humanização de Baleia</b> e <b>desumanização social dos retirantes</b>.</div><div class="video-lesson"><span>🎥 REVISÃO RÁPIDA • PMMG</span><h3>Vidas Secas em 5 minutos — PMMG</h3><p>Resumo rápido para reforçar personagens e temas.</p><iframe src="https://www.youtube.com/embed/jeoWc-rAm_4" title="Vidas Secas resumo PMMG" allowfullscreen loading="lazy"></iframe></div>`,quiz:[
{question:"O sonho recorrente de Sinhá Vitória envolve:",options:["Uma cama de couro.","Um automóvel.","Uma viagem à Europa.","Uma fazenda de café."],answer:0,explanation:"A cama simboliza conforto e estabilidade desejados.",tip:"Pequeno objeto, grande significado."},
{question:"Baleia é:",options:["A cachorra da família.","Uma professora.","A mãe de Fabiano.","Uma cidade."],answer:0,explanation:"Baleia é a cachorra da família e personagem marcante.",tip:"Seu capítulo é central."},
{question:"A dificuldade de linguagem de Fabiano se relaciona:",options:["À exclusão e à dificuldade de se defender socialmente.","À formação universitária.","À profissão de escritor.","A um jogo cômico sem consequência."],answer:0,explanation:"A limitação verbal tem dimensão social.",tip:"Linguagem também é poder."},
{question:"O tratamento dado a Baleia pode ser entendido como:",options:["Humanização do animal.","Eliminação de qualquer interioridade.","Descrição científica.","Ausência de afeto."],answer:0,explanation:"O narrador atribui interioridade e sensibilidade a Baleia.",tip:"Compare com a desumanização dos humanos."},
{question:"Sinhá Vitória é caracterizada também por:",options:["Resistência e desejo de melhorar a vida.","Desinteresse completo pelo futuro.","Ser a antagonista principal.","Viver fora do sertão."],answer:0,explanation:"Ela projeta uma vida mais digna para a família.",tip:"Sonho e resistência."},
{question:"A opressão em Vidas Secas:",options:["Vai além da seca e inclui relações sociais de poder.","É inexistente.","É somente familiar.","É exclusivamente religiosa."],answer:0,explanation:"Exploração e abuso institucional aparecem na obra.",tip:"Natureza + sociedade."}
]},
6:{title:"Vidas Secas — temas, símbolos e comparação das obras",subtitle:"Literatura • Aula 06 • Revisão comparativa",time:"55 min",content:`<div class="edital-badge">📋 EDITAL PMMG • REVISÃO DAS DUAS OBRAS</div><h3>Vidas Secas</h3><p>Economia de linguagem, sobrevivência, seca, desigualdade, opressão, incomunicabilidade e ciclo de retirada são eixos fortes.</p><h3>Campo Geral</h3><p>Infância, sensibilidade, família, natureza, violência, perda, linguagem rosiana e amadurecimento de Miguilim são eixos fortes.</p><h3>Não misture</h3><p><b>Miguilim / Mutúm / Dito / Guimarães Rosa</b> pertencem a Campo Geral. <b>Fabiano / Sinhá Vitória / Baleia / sertão nordestino / Graciliano Ramos</b> pertencem a Vidas Secas.</p><div class="lesson-example"><b>Estratégia de prova:</b> antes de avaliar a afirmação, identifique a qual obra, personagem e espaço ela pertence.</div><div class="gold-rule">🎯 REGRA DE OURO: faça uma tabela mental das duas obras para evitar trocas de personagens e características.</div>`,quiz:[
{question:"Miguilim pertence a:",options:["Campo Geral.","Vidas Secas.","Memórias Póstumas.","O Cortiço."],answer:0,explanation:"Miguilim protagoniza Campo Geral.",tip:"Miguilim → Rosa."},
{question:"Baleia pertence a:",options:["Vidas Secas.","Campo Geral.","Grande Sertão: Veredas.","Dom Casmurro."],answer:0,explanation:"Baleia é a cachorra da família de Fabiano.",tip:"Baleia → Graciliano."},
{question:"Mutúm está associado a:",options:["Campo Geral.","Vidas Secas.","Capitães da Areia.","Iracema."],answer:0,explanation:"É o espaço central da família de Miguilim.",tip:"Mutúm → Minas."},
{question:"O ciclo de retirada é especialmente importante em:",options:["Vidas Secas.","Campo Geral apenas.","Nenhuma das duas.","Uma peça teatral."],answer:0,explanation:"A estrutura cíclica reforça a condição dos retirantes.",tip:"Fuga da seca e recomeço."},
{question:"A descoberta da miopia é marcante em:",options:["Campo Geral.","Vidas Secas.","Ambas exatamente do mesmo modo.","Nenhuma."],answer:0,explanation:"Miguilim descobre a miopia.",tip:"Óculos → Miguilim."},
{question:"A cama de couro é desejo de:",options:["Sinhá Vitória.","Nhanina.","Miguilim.","Dito."],answer:0,explanation:"É sonho de Sinhá Vitória em Vidas Secas.",tip:"Cama → estabilidade."}
]},
7:{title:"🏆 Prova Final — Literatura",subtitle:"Literatura • Avaliação final • Campo Geral + Vidas Secas",time:"45 min",content:`<div class="edital-badge">🏆 PROVA FINAL • LITERATURA PMMG</div><h3>Fechamento da disciplina</h3><p>Esta prova reúne 20 questões e mistura as duas obras exigidas no edital: <b>Campo Geral</b>, de João Guimarães Rosa, e <b>Vidas Secas</b>, de Graciliano Ramos.</p><p>As alternativas são embaralhadas em cada tentativa.</p><div class="gold-rule">🎯 APROVAÇÃO: mínimo de <b>70%</b>. Se não atingir, revise as aulas e o Caderno de Erros.</div>`,quiz:[
{question:"Assinale a associação correta:",options:["Miguilim — Campo Geral.","Miguilim — Vidas Secas.","Baleia — Campo Geral.","Fabiano — Campo Geral."],answer:0,explanation:"Miguilim protagoniza Campo Geral.",tip:"Separe as personagens por obra."},
{question:"Vidas Secas foi escrito por:",options:["Graciliano Ramos.","Guimarães Rosa.","Machado de Assis.","Drummond."],answer:0,explanation:"Graciliano Ramos é o autor.",tip:"Graciliano → Vidas Secas."},
{question:"Campo Geral acompanha principalmente:",options:["A experiência e o amadurecimento de Miguilim.","A carreira militar de Fabiano.","Uma família urbana no Rio.","Uma investigação criminal."],answer:0,explanation:"Miguilim e sua formação são centrais.",tip:"Infância e percepção."},
{question:"Em Vidas Secas, a seca:",options:["Articula-se a problemas sociais e econômicos.","É a única dificuldade existente.","Não interfere na vida da família.","É apenas um sonho."],answer:0,explanation:"A obra também aborda exploração, pobreza e opressão.",tip:"Natureza + sociedade."},
{question:"Dito é personagem de:",options:["Campo Geral.","Vidas Secas.","Nenhuma das obras.","Vidas Secas e narrador."],answer:0,explanation:"Dito é irmão de Miguilim.",tip:"Dito → Miguilim."},
{question:"Sinhá Vitória deseja especialmente:",options:["Uma cama de couro.","Óculos para Miguilim.","Mudar para Mutúm.","Ser escritora."],answer:0,explanation:"A cama simboliza estabilidade e conforto.",tip:"Objeto simbólico de Vidas Secas."},
{question:"A descoberta da miopia ocorre com:",options:["Miguilim.","Fabiano.","Sinhá Vitória.","Baleia."],answer:0,explanation:"Miguilim passa a enxergar nitidamente com óculos.",tip:"Visão → Campo Geral."},
{question:"A humanização de Baleia contrasta com:",options:["A desumanização social vivida pelos retirantes.","A riqueza da família.","A vida urbana confortável.","A ausência de sofrimento."],answer:0,explanation:"Esse contraste é importante na obra.",tip:"Animal humanizado x humanos oprimidos."},
{question:"A linguagem de Guimarães Rosa em Campo Geral destaca:",options:["Oralidade, regionalismo e invenção expressiva.","Somente linguagem jurídica.","Ausência de marcas regionais.","Vocabulário técnico científico."],answer:0,explanation:"A elaboração linguística é característica rosiana.",tip:"Rosa recria a linguagem."},
{question:"A estrutura de Vidas Secas é frequentemente descrita como:",options:["Cíclica, com capítulos relativamente autônomos.","Teatral em cinco atos.","Diário em primeira pessoa.","Poema épico."],answer:0,explanation:"O movimento de retirada e recomeço reforça o ciclo.",tip:"Início e fim se correspondem."},
{question:"O Mutúm pertence ao universo de:",options:["Campo Geral.","Vidas Secas.","Ambas as obras.","Nenhuma das obras."],answer:0,explanation:"É o espaço central de Campo Geral.",tip:"Mutúm → Minas Gerais."},
{question:"Fabiano apresenta dificuldade de expressão que se relaciona:",options:["À exclusão e às relações de poder.","À formação acadêmica.","Ao trabalho de jornalista.","A um recurso sem função social."],answer:0,explanation:"A limitação verbal participa da condição social da personagem.",tip:"Linguagem é poder."},
{question:"Qual par está correto?",options:["Guimarães Rosa — Campo Geral.","Guimarães Rosa — Vidas Secas.","Graciliano Ramos — Campo Geral.","Miguilim — Vidas Secas."],answer:0,explanation:"Guimarães Rosa escreveu Campo Geral.",tip:"Autor e obra."},
{question:"Um tema comum às duas obras é:",options:["A dureza da vida no sertão e relações humanas complexas.","Tecnologia digital.","Vida aristocrática europeia.","Exploração espacial."],answer:0,explanation:"As duas obras trabalham experiências humanas em ambientes sertanejos, embora de modos diferentes.",tip:"Compare sem igualar."},
{question:"Para a prova da PMMG, Literatura no edital trabalhado cobra:",options:["Campo Geral e Vidas Secas.","Somente poesia de Camões.","Dom Casmurro e O Cortiço.","Apenas teoria literária abstrata."],answer:0,explanation:"São as duas obras expressamente indicadas.",tip:"Duas obras obrigatórias."}
,{question:"Em Campo Geral, a focalização narrativa aproxima o leitor de:",options:["Miguilim e sua percepção infantil.","Fabiano e sua vida de retirante.","Baleia como narradora.","Um juiz urbano."],answer:0,explanation:"A narrativa acompanha de perto a percepção de Miguilim.",tip:"Terceira pessoa pode focalizar uma personagem."},
{question:"Em Vidas Secas, o Soldado Amarelo evidencia:",options:["Abuso de autoridade e impotência social de Fabiano.","Prosperidade da família.","A infância de Miguilim.","A descoberta da miopia."],answer:0,explanation:"O episódio expõe relações de poder e submissão.",tip:"Fabiano enfrenta também opressão social."},
{question:"Qual comparação está correta?",options:["Campo Geral enfatiza Miguilim; Vidas Secas acompanha retirantes.","As duas obras são narradas por Miguilim.","Baleia e Dito pertencem a Campo Geral.","As duas se passam no Mutúm."],answer:0,explanation:"As obras têm universos próprios e não devem ser confundidas.",tip:"Separe personagens, autores e espaços."},
{question:"A economia de linguagem é especialmente associada a:",options:["Vidas Secas, de Graciliano Ramos.","Campo Geral como texto jurídico.","Nenhuma das obras.","Somente aos diálogos de Dito."],answer:0,explanation:"A escrita enxuta é marca importante de Graciliano Ramos.",tip:"Graciliano → linguagem concisa."},
{question:"Uma revisão eficiente das duas obras deve relacionar:",options:["Autor, personagens, espaço, narrador, temas e episódios centrais.","Somente datas de publicação.","Apenas nomes dos autores.","Personagens misturados das duas obras."],answer:0,explanation:"A prova pode cruzar diferentes elementos das obras.",tip:"Faça uma ficha mental para cada obra."}
]}
};
