(()=>{
'use strict';
const EXAMS=[
 {year:2026,status:'pending',title:'CFSd / Soldado PMMG',note:'Nenhuma prova geral de Soldado 2026 foi cadastrada porque ainda não encontramos uma prova aplicada e verificável.',links:[]},
 {year:2025,status:'verified',title:'CFSd PMMG 2025',note:'Prova e gabarito definitivo localizados em banco público de provas.',links:[['Abrir prova e gabarito','https://vanguardamilitar.com/banco-de-provas-cfsd-pmmg/']]},
 {year:2024,status:'special',title:'PMMG 2024',note:'Foi localizado material de Soldado Especialista, mas não será tratado como prova geral CFSd. Mantido separado para não misturar concursos.',links:[]},
 {year:2023,status:'verified',title:'CFSd PMMG 2023',note:'Prova e gabarito definitivo localizados em banco público de provas.',links:[['Abrir prova e gabarito','https://vanguardamilitar.com/banco-de-provas-cfsd-pmmg/']]},
 {year:2022,status:'verified',title:'CFSd QPPM/2022',note:'Caderno identificado pelo Edital DRH/CRS nº 06/2021. A prova possui 40 questões.',links:[['Abrir caderno da prova','https://alunomilitar.com.br/wp-content/uploads/2023/03/prova-pmmg-2021-2022.pdf']]},
 {year:2021,status:'verified',title:'CFSd PMMG 2021',note:'Prova e gabarito definitivo localizados em banco público de provas.',links:[['Abrir prova e gabarito','https://vanguardamilitar.com/banco-de-provas-cfsd-pmmg/']]},
 {year:2020,status:'pending',title:'CFSd / Soldado PMMG',note:'Ainda não foi cadastrada uma prova geral de Soldado PMMG verificável para este ano. Não vamos preencher com prova de Bombeiros, CFO ou Especialista.',links:[]}
];
const STATUS={verified:['✓ VERIFICADA','verified'],pending:['○ NÃO LOCALIZADA','pending'],special:['! OUTRA MODALIDADE','special']};
function esc(s){return String(s).replace(/[&<>\"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;'}[c]));}
function css(){if(document.getElementById('v104css'))return;const st=document.createElement('style');st.id='v104css';st.textContent=`
#pastExamsV104{padding-bottom:110px}.v104-summary{margin:14px 0;padding:16px;border:1px solid var(--line);border-radius:18px;background:linear-gradient(145deg,rgba(218,181,89,.10),rgba(255,255,255,.02))}.v104-summary strong{font-size:20px}.v104-summary p,.v104-card p{color:var(--muted);line-height:1.45}.v104-list{display:grid;gap:10px}.v104-card{border:1px solid var(--line);border-radius:18px;padding:15px;background:rgba(255,255,255,.025)}.v104-top{display:flex;align-items:flex-start;justify-content:space-between;gap:10px}.v104-year{font-size:25px;font-weight:900}.v104-badge{font-size:9px;font-weight:900;padding:7px 9px;border-radius:999px;border:1px solid var(--line)}.v104-badge.verified{color:#9ee7b0;border-color:rgba(90,210,120,.3);background:rgba(90,210,120,.08)}.v104-badge.pending{color:var(--muted)}.v104-badge.special{color:#f0cb72;border-color:rgba(240,203,114,.3)}.v104-title{font-weight:800;margin-top:5px}.v104-actions{display:flex;gap:8px;flex-wrap:wrap;margin-top:12px}.v104-actions a{display:inline-flex;text-decoration:none;align-items:center;justify-content:center;padding:11px 13px;border-radius:12px;background:var(--gold);color:#101010;font-weight:900;font-size:11px}.v104-empty{font-size:10px;color:var(--muted);padding-top:7px}.v104-foot{margin-top:12px;padding:12px;border:1px dashed var(--line);border-radius:14px;color:var(--muted);font-size:10px;line-height:1.45}`;document.head.appendChild(st)}
function render(){css();const ok=EXAMS.filter(x=>x.status==='verified').length;const sum=document.getElementById('pastExamsSummaryV104'),list=document.getElementById('pastExamsListV104');if(!sum||!list)return;sum.innerHTML=`<div class="v104-summary"><span class="kicker">COLEÇÃO 2020–2026</span><strong>${ok} provas verificadas</strong><p>O Missão PMMG só marca como disponível o que foi conferido como prova de Soldado/CFSd. Outros concursos não entram no lugar.</p></div>`;list.innerHTML=`<div class="v104-list">${EXAMS.map(x=>{const [label,cls]=STATUS[x.status];return `<article class="v104-card"><div class="v104-top"><div><div class="v104-year">${x.year}</div><div class="v104-title">${esc(x.title)}</div></div><span class="v104-badge ${cls}">${label}</span></div><p>${esc(x.note)}</p>${x.links.length?`<div class="v104-actions">${x.links.map(([t,u])=>`<a href="${esc(u)}" target="_blank" rel="noopener noreferrer">${esc(t)} ↗</a>`).join('')}</div>`:`<div class="v104-empty">Sem link cadastrado até existir uma fonte compatível e verificável.</div>`}</article>`}).join('')}</div><div class="v104-foot">🔒 Regra da coleção: não substituir anos ausentes por provas de Bombeiros, CFO ou quadros especialistas. Assim seu histórico de treino continua fiel ao concurso de Soldado PMMG.</div>`}
window.openPastExamsV104=function(){document.querySelectorAll('.screen').forEach(x=>x.classList.remove('active'));const s=document.getElementById('pastExamsV104');if(s){s.classList.add('active');window.scrollTo(0,0);render()}};
document.addEventListener('DOMContentLoaded',render);
})();
